### ISSUE TITLE
micropython-experiments - 'panic' is declared but not used

### ISSUE THREAD

**Issue by UNIcodeX** [yglukhov/nimpy#102]
When following instructions for the micropython example, I get the following error upon issuing `make` in the `~/micropython/ports/unix` port directory.

```
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
echo 'import mymodule, panicoverride, nimpy/py_micro; py_micro.private_mp_implement_glue()' > nim/main.nim
nim c --nimcache:nim/intermediate --genDeps --compileOnly --noMain --os:standalone --gc:none nim/main.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: main [Processing]
Hint: mymodule [Processing]
Hint: panicoverride [Processing]
panicoverride.nim(3, 6) Hint: 'panic' is declared but not used [XDeclaredButNotUsed]
main.nim(1, 38) Error: cannot open file: nimpy/py_micro
```

Thanks for the work on this. Very interesting indeed.

This build process does seem to be for generating a custom build of micropython with an extension module written in Nim. I'm wondering if it were possible to create a module that is importable as a stand alone library file.

**Comment by UNIcodeX** [comment]
I was able to get past that by copying the contents of the `nimpy` directory to the `~/micropython/ports/unix/nim/` directory. Now getting:

```
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
echo 'import py_types, py_utils, py_micro, mymodule, raw_buffers, py_lib, panicoverride, nimpy/py_micro; py_micro.private_mp_implement_glue()' > nim/main.nim
nim c --nimcache:nim/intermediate --genDeps --compileOnly --noMain --os:standalone --gc:none nim/main.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: main [Processing]
Hint: py_types [Processing]
Hint: py_utils [Processing]
Hint: strscans [Processing]
Hint: macros [Processing]
Hint: parseutils [Processing]
Hint: strutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
/usr/lib/nim/pure/unicode.nim(291, 4) Error: type mismatch: got <seq[char]> but expected 'string'
```

**Comment by yglukhov** [comment]
> I'm wondering if it were possible to create a module that is importable as a stand alone library file.

I don't think that's supported, but either way, that's a micropython question/limitation/issue. I will look at extension approaches as soon as I know it's possible in C.

>  Now getting...

Apparently you went too far in experiments and hit this nim bug https://github.com/nim-lang/Nim/issues/9762.

**Comment by UNIcodeX** [comment]
Sounds great! Thanks again.
