### ISSUE TITLE
Can't use http client 

### ISSUE THREAD

**Issue by sonic182** [yglukhov/nimpy#109]
Compiling with -d:ssl (required for http client) I'm having 

SIGSEGV: Illegal storage access. (Attempt to read from nil?)

importing *.so

**Comment by yglukhov** [comment]
Can't reproduce. Please provide the exact steps to reproduce, along with the sample source code.

**Comment by yglukhov** [comment]
No response, closing.

**Comment by sonic182** [comment]
I coudn't reproduce neither, also I lost the code that gave me errors....
