### ISSUE TITLE
PyList_New is nil

### ISSUE THREAD

**Issue by andreaferretti** [yglukhov/nimpy#11]
I have a function that returns a sequence, and when trying to access these values from python I get a `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`.

In trying to debug this, I added some debug information to nimpy, and it turns out that this happens in [nimArrToPy](https://github.com/yglukhov/nimpy/blob/master/nimpy.nim#L899-L904), where `pyLib.PyList_New` is nil.

Strangely enough, other functions from pyLib, such as `Py_BuildValue`, are not nil.

I struggle to provide an example, because when I try to find a minimal case, the issue disappears. Still, maybe you have some idea where I should start looking to understand whether pyLis is initialized correctly.

What is especially confusing is that these symbols seem to be all loaded with a template [load](https://github.com/yglukhov/nimpy/blob/master/nimpy.nim#L547-L550) which reads

```nim
template load(v: untyped, name: cstring) =
  maybeLoad(v, name)
  if pyLib.v.isNil:
    raise newException(Exception, "Symbol not loaded: " & $name)
```

so apparently it shouldn't be possible that pyLib is partially loaded :-?

**Comment by andreaferretti** [comment]
I have tried adding this snippet in the body of `nimArrToPy`:

```nim
echo pyLib.Py_BuildValue.isNil
echo pyLib.PyTuple_New.isNil
echo pyLib.PyTuple_Size.isNil
echo pyLib.PyTuple_GetItem.isNil
echo pyLib.PyTuple_SetItem.isNil
echo pyLib.Py_None.isNil
echo pyLib.PyType_Ready.isNil
echo pyLib.PyType_GenericNew.isNil
echo pyLib.PyModule_AddObject.isNil
echo pyLib.PyList_New.isNil
echo pyLib.PyList_Size.isNil
echo pyLib.PyList_GetItem.isNil
echo pyLib.PyList_SetItem.isNil
```

and I get

```nim
false
true
true
true
true
true
true
true
true
true
true
true
true
```

so apparently `Py_BuildValue` is the only symbol loaded (among the ones I tested)

**Comment by andreaferretti** [comment]
I confirm that after loading, the symbols are indeed not nil. But later, they all become nil.

I don't mind debugging, but unfortunately I am not familiar with how to work with a debugger... :-(

**Comment by yglukhov** [comment]
Ping me on gitter pls

**Comment by yglukhov** [comment]
Fixed, but depends on https://github.com/nim-lang/Nim/pull/7885

**Comment by andreaferretti** [comment]
Great, thank you! Nimpy is really improving fast!
