### ISSUE TITLE
Add support for types and methods

### ISSUE THREAD

**Issue by Keithcat1** [yglukhov/nimpy#115]
Hi,
Nimpy is a really awesome tool for wrapping Nim.
However, making types accessible from Python currently extreemly hard. The best I can think of is using a table with IDs, and sending those IDs to Python and getting back the IDs and looking up objects in the table.
Can you please add a way to define what types are vissible from Python, which properties are vissible, and which methods are visible please?

**Comment by yglukhov** [comment]
Not sure I understand the question. The only visible stuff from python is what you mark with `{.exportpy.}`. Currently nimpy doesn't allow exporting types/methods in oop way, but the usual way works.

```nim
# foo.nim
type Foo = ref object
  a: int

proc newFoo*(): Foo {.exportpy.} = result.new()
proc getA*(f: Foo): int {.exportpy.} = f.a
proc setA*(f: Foo, a: int) {.exportpy.} = f.a = a
```
```py
# foo.py
import foo
f = foo.newFoo()
foo.setA(f, 5)
print(foo.getA(f))
```
There's also non-ref object and tuple marshalling, but I suppose that's not what you're asking about?

**Comment by Albus70007** [comment]
Maybe you can find this interesting @yglukhov
i am not sure if this is the rel issue, but this works for types (not methods)
https://stackoverflow.com/questions/1305532/convert-nested-python-dict-to-object

**Comment by lhupfeldt** [comment]
Making types work, even without methods, would greatly increase the usability of this to a point where many python modules could actually be implemented in nim.
