### ISSUE TITLE
Lambda support

### ISSUE THREAD

**Issue by juancarlospaco** [yglukhov/nimpy#117]
Make a Nim anonymous `proc`/`func` become a Python lambda.

```nim
( func (arg: int): int {.exportpy.} = arg * 2 )
```
Kinda like this, but on C ABI:
```python
lambda arg: arg * 2
```

:slightly_smiling_face:

**Comment by yglukhov** [comment]
You can already pass nim functions to python, i don't understand what's missing. Please provide a more elaborate sample.

**Comment by juancarlospaco** [comment]
Ok.
