### ISSUE TITLE
Can you make the c names prettier?

### ISSUE THREAD

**Issue by flenniken** [yglukhov/nimpy#120]
The nimformat project on github uses nimpy to build a python module that can be packaged and installed with pip.  The package includes the c source files and pip compiles them to build the python module on the target machine.

The nimpy c files names have drastically changed since nim version .19.

The names used to be:

```
nimformat.c
nimpy_nimpy.c
nimpy_py_lib.c
nimpy_py_types.c
nimpy_py_utils.c 
```

and now with nim 1.0.2 they are:

```
@m..@s..@s.nimble@spkgs@snimpy-@hc8ec14a@snimpy.nim.c
@m..@s..@s.nimble@spkgs@snimpy-@hc8ec14a@snimpy@spy_lib.nim.c
@m..@s..@s.nimble@spkgs@snimpy-@hc8ec14a@snimpy@spy_types.nim.c
@m..@s..@s.nimble@spkgs@snimpy-@hc8ec14a@snimpy@spy_utils.nim.c
@mnimformat.nim.c
```

The standard nim files now have the ".nim.c" suffix but their names are more regular, for example `stdlib_dynlib.c` changed to `stdlib_dynlib.nim.c`.

Do you have control of the nimpy c filenames and can you make the prettier?

https://github.com/UNIcodeX/nimformat/

**Comment by flenniken** [comment]
I just discovered the @ names are platform dependent.  The names shown before are from Ubuntu 18.04.1 LTS and the ones here are from a Mac:

```
@m..@s..@snimpy@snimpy.nim.c
@m..@s..@snimpy@snimpy@spy_lib.nim.c
@m..@s..@snimpy@snimpy@spy_types.nim.c
@m..@s..@snimpy@snimpy@spy_utils.nim.c
nimformat.nim.c
```

The names need to be the same to work in a cross platform setup.py file.

**Comment by yglukhov** [comment]
C files generated by nim are neither cross-platform nor architecture agnostic. Generally you want to use a different set of C sources for every arch+platform combination, and I'd search for such capabilities in your python packaging system. This is totally out of nimpy control.
