### ISSUE TITLE
Add to Conda Forge

### ISSUE THREAD

**Issue by Benjamin-Lee** [yglukhov/nimpy#123]
I'm working on distributing a Nim accelerator for a scientific Python package. My users almost certainly don't have Nim installed but do probably have Conda, so I was hoping to make it easier on them by adding Nim and Nimpy as Conda dependencies.

Nim is listed on Conda Forge but Nimpy isn't. Could we get it added?

**Comment by yglukhov** [comment]
I don't mind, but I'm not gonna do it, sorry.
