### ISSUE TITLE
Implement Instagram trick: No GC Python

### ISSUE THREAD

**Issue by juancarlospaco** [yglukhov/nimpy#124]
Instagram published a trick with CPython GC to disable it completely and improve performance,
I was wondering if that trick can be integrated into Nimpy, at least as Experimental feature,
kinda like have a helper function that does this but at C level, seems to work, code is short,
something like `nimpy.disablePythonGC()` or similar, read the following post,
mainly the part under the title "Attempt 4: Final step for shutting down GC: No cleanup":

https://instagram-engineering.com/dismissing-python-garbage-collection-at-instagram-4dca40b29172

If its not possible for whatever reason, feel free to just close the issue.
:slightly_smiling_face:

**Comment by yglukhov** [comment]
Meh, nimpy isn't the place for python tips and tricks. As long as it's possible to do this trick with nimpy (without patching nimpy) we're fine.
