### ISSUE TITLE
How to workaround namespace collisions?

### ISSUE THREAD

**Issue by WesleyYue** [yglukhov/nimpy#127]
I'm trying to play around with a toy example

```
let np = pyImport("numpy")
let test = np.zeros((2, 3), dtype = np.int32)
```

However, I'm running into an issue where nim seems to be interpreting np.int32 as int32(np) due to the unified call syntax, where int32 is the system.int32 procedure from nim. Specifically, the error I get is `Error: type mismatch: got <PyObject> but expected 'int32`. Is there a way for me to work around this and specify that I want the numpy.int32 type?

I know that I can do np.dtype("int32") for this specific example, but is there a general solution to this issue?

**Comment by yglukhov** [comment]
You can use `np.getProperty("int32")` for such cases.

**Comment by timotheecour** [comment]
also useful for illegal nim identifiers eg:
```nim
let matplotlib = pyImport("matplotlib")
# echo matplotlib.`__version__`.to(string) # disallowed, but see https://github.com/timotheecour/Nim/issues/339
echo matplotlib.getProperty("__version__").to(string)
```
