### ISSUE TITLE
Importing nim module in python breaks argparse

### ISSUE THREAD

**Issue by WesleyYue** [yglukhov/nimpy#128]
Does the compiled python module perform some magic with parsing arguments? I'm running into an issue where I have a python script that uses argparse, and when I import the .so module compiled from nim with nimpy, it breaks the argparse in the python script as if the imported python module had an argparse of its own and ate up all the arguments. (Similar to this https://bugs.python.org/issue36561). I tried importing things explicitly with `from nim_module import function` but continued to have the same problem. Any idea on how I can fix this?

**Comment by WesleyYue** [comment]
I figured out the issue. It was because I had a few lines of code in the main namespace of the nim module that I didn't realize. Once I removed that code my python argparse worked fine. I found that even when wrapping the module "global" code in the nim module with when isMainModule did not fix the problem. It seems like that could be a bug?

**Comment by yglukhov** [comment]
Yeah I'm afraid it's just how nim works. Even if you compile an .so there still is a "main" module which is what you're observing. I think it is reasonable for nim to do that but you could try raise the issue in the nim tracker.
