### ISSUE TITLE
How to pass a mutable string from python?

### ISSUE THREAD

**Issue by andreaferretti** [yglukhov/nimpy#129]
Is there a way to pass a string from Python and store it in a Nim object in such a way that changes done to the Nim object will reflect in Python? I tried

```nim
import nimpy

type Foo = ref object
  data: string

proc initFoo(data: string): Foo {.exportpy.} =
  new result
  shallowCopy(result.data, data)

proc changeFoo(foo: Foo) {.exportpy.} =
  foo.data[2] = 'x'

proc printFoo(foo: Foo) {.exportpy.} =
  echo foo.data
```

but the underlying string is copied from python.

```python
import example

s = "foo"
foo = example.initFoo(s)
example.changeFoo(foo)
print(s) # foo
example.printFoo(foo) # fox
```

I tried changing the parameter of `initFoo` to `var string` or `ref string`, but both cases fail to compile

**Comment by Vindaar** [comment]
I haven't ever worked with Python strings with nimpy, but I imagine it should be possible a similar way as it works for numpy arrays. For instance in this example here:

https://github.com/yglukhov/nimpy/issues/114#issuecomment-531504502

As far as I can tell a Python string is a `PyBytesObject`: https://docs.python.org/3/c-api/bytes.html

I don't have the time to play around with this myself at the moment. If you want I can see if I can make it work tomorrow. :)

**Comment by yglukhov** [comment]
Nimpy string marshalling is deep copy, no way around. But you can use PyObject to represent the string, then youll get the semantics you need.

**Comment by andreaferretti** [comment]
I was about to try your suggestions, but then

@Vindaar 
> edit: nevermind this comment. Listen to yglukhov below.

@yglukhov 
> EDIT: But note that it still wouldn't work because python strings are immutable :)

:-)

In any case, I noticed that  https://github.com/yglukhov/nimpy/issues/114 is about passing Pillow pixel data. This is exactly what I am trying to do here: since `image.tobytes()` returns a byte array, I was wrapping that as a string in the Nim side (not that I especially like that, but it seems to be a standard way to represent bytes in Nim, for instance also [NimPng](https://github.com/jangko/nimPNG) uses it to represent the undelying image buffer).

The [example](https://github.com/yglukhov/nimpy/issues/114#issuecomment-531504502) of @Vindaar seems to cover exactly this case, but it is still not completely clear to me how to use it. What I would like is to convert back and forth (without copies) between a PIL Image and some kind of Nim object with a structure like

```nim
type Image = ref object
  width, height: int
  data: string # or seq[byte]
```

and `takeBuffer` does not do that - instead it wraps the buffer with `initNdArray` from numpy

**Comment by yglukhov** [comment]
> without copies...

Step 1. Use `PyObject` instead of `string`. This way you get no copies.
Step 2 (optional). If you do lots of batched accesses to the underlying buffer and want to optimize for it, use the `raw_buffers` api on top.

**Comment by andreaferretti** [comment]
> Step 1. Use PyObject instead of string. This way you get no copies.

Bu then I haev a PyObject :-) . How do I access the underlying buffer? Or for that matter, how do I do anything on a PyObject?

**Comment by yglukhov** [comment]
Just like you would do it in python.
```nim
import nimpy
let np = pyImport("numpy")
let myPyObj: PyObject = np.`array`([1, 2]) # Type annotation is for clarity
echo myPyObj
myPyObj[0] = 5 # Here we access PyObject
echo myPyObj
echo myPyObj.ndim # Here we access it again
discard myPyObj.fill(10) # And again
echo myPyObj
```

**Comment by andreaferretti** [comment]
Uh, wow! How does it even compile? Nimpy is much more advanced than I had thought! :-D

**Comment by yglukhov** [comment]
Oh, come on, it's in the README :)

**Comment by yglukhov** [comment]
So problem solved I suppose?

**Comment by andreaferretti** [comment]
Yeah, still have to experiment a bit, but now everything is clear. Thanks a lot!
