### ISSUE TITLE
No module named 'encodings'

### ISSUE THREAD

**Issue by slime496** [yglukhov/nimpy#130]
When I do import some python module in nim, It shows such an error.
When I do "import encodings" in python code, it just works fine.

![image](https://user-images.githubusercontent.com/60994410/74999878-bf082b80-5497-11ea-90d3-3ba27cd88ce9.png)
Just ran the example code above and got that error

![image](https://user-images.githubusercontent.com/60994410/74999809-92ecaa80-5497-11ea-827b-1911a1fe2671.png)

win10 64bit
Python 3.7.1

**Comment by slime496** [comment]
`import nimpy
let os = pyImport("os")
echo "Current dir is: ", os.getcwd().to(string)

# sum(range(1, 5))
let py = pyBuiltinsModule()
let s = py.sum(py.range(0, 5)).to(int)
assert s == 10`

Just ran the example code and got that error
![image](https://user-images.githubusercontent.com/60994410/74999809-92ecaa80-5497-11ea-827b-1911a1fe2671.png)

**Comment by drewbitt** [comment]
From what I understand from https://bugs.python.org/issue35596, this is a bug with 3.7.1. This was fixed in 3.7.2, though after it first came out (see UPDATED 2019-01-09 in windows users)

**Comment by yglukhov** [comment]
Not a nimpy issue? Closing.
