### ISSUE TITLE
How do I use builtin 'type' as member variable name

### ISSUE THREAD

**Issue by Dwood15** [yglukhov/nimpy#131]
I'm trying to define a python class in NIm, but it turns out it uses a nim-builtin keyword `type` as a member variable. How do I express this in Nimpy?

**Comment by Albus70007** [comment]
i think you should use \`type\` to let nim now its not a keyword

**Comment by yglukhov** [comment]
> I'm trying to define a python class in NIm

Exporting nim types as python classes is not yet supported, if that's what you mean.

> it uses a nim-builtin keyword type as a member variable. How do I express this in Nimpy?

Use backticks, as @Albus70007 suggests

**Comment by timotheecour** [comment]
not 100% related to this issue but I was searching for how to use python's type, and here's the solution:
```nim
when true:
  import pkg/nimpy
  let os = pyImport("os")
  let py = pyBuiltinsModule()
  echo py.type(os)
```
