### ISSUE TITLE
Not importing module

### ISSUE THREAD

**Issue by Albus70007** [yglukhov/nimpy#132]
Hello, i have this module "rlbot", i try to import it as:
```nim
let rlbot = pyImport("rlbot")
```
but i get: 

> Error: unhandled exception: <class 'ModuleNotFoundError'>: No module named 'rlbot' [Exception]

which is weird, because i do have that module in my python version, and i know i am loading that version since:
```nim
let pysys = pyImport("sys")
echo pysys.version
```
prints the same as running python in the terminal
> (3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)])

from nim, and
> (Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)])

from the terminal, any help?

**Comment by yglukhov** [comment]
Try comparing `sys.path` instead of `sys.version`.

**Comment by Albus70007** [comment]
ok, a lot of diferences, how can i fix it?
its messing with multiple installations, vs code one, stackless...

**Comment by Albus70007** [comment]
@yglukhov i want to let you know, adding the place where it should be looking for the libray fixes the issue, nevertheless, i think you should have a look at why does it mess  up with multiple installations.
quick fix:
```nim
discard pysys.path.append("C:\\Users\\porra\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages")
```

**Comment by yglukhov** [comment]
Can you show the `sys.path` output from nimpy and python pls?

**Comment by Albus70007** [comment]
sure, here you go:
```['C:\\Users\\porra\\AppData\\Local\\Programs\\Python\\Python37\\python37.zip', 'C:\\Users\\porra\\AppData\\Local\\Programs\\Python\\Stackless37\\Lib', 'C:\\Users\\porra\\AppData\\Local\\Programs\\Python\\Stackless37\\DLLs', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\DLLs', 'C:\\Users\\porra\\OneDrive\\Escritorio\\Python_projectos\\Nim\\MLnim', 'C:\\Users\\porra\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\lib\\site-packages']```

**Comment by yglukhov** [comment]
Both outputs please? One from nimpy, one from python. And mark which is which :)

**Comment by Albus70007** [comment]
ok, updated
