### ISSUE TITLE
Nim tuples

### ISSUE THREAD

**Issue by drewbitt** [yglukhov/nimpy#133]
I'm having an issue I can't seem to resolve. 

Python example function: 
```python
lnList = []
for thing in things:
        data = {'title': thing.title,
                'url': thing.url}
        lnList.append(data)
return lnList
```
So in nim this would be a sequence containing tuples. 
```nim
let nu = pyImport("example")
nu.function.to(seq[tuple[title: string, url: string]])
```
Without the .to, this returns a PyObject `[{'title': 'example', 'url': 'example'}]`
With the .to, errors: 
```
src\src\util\nu.nim(14) nu
C:\Users\andys-pc\.nimble\pkgs\nimpy-0.1.0\nimpy.nim(1159) to
C:\Users\andys-pc\.nimble\pkgs\nimpy-0.1.0\nimpy.nim(448) pyObjToNim
C:\Users\andys-pc\.nimble\pkgs\nimpy-0.1.0\nimpy.nim(495) pyObjToNimSeq
C:\Users\andys-pc\.nimble\pkgs\nimpy-0.1.0\nimpy.nim(484) pyObjFillArray
C:\Users\andys-pc\.nimble\pkgs\nimpy-0.1.0\nimpy.nim(466) pyObjToNim
C:\Users\andys-pc\.nimble\pkgs\nimpy-0.1.0\nimpy.nim(545) pyObjToNimTuple
C:\Users\andys-pc\.nimble\pkgs\nimpy-0.1.0\nimpy.nim(403) raiseConversionError
Error: unhandled exception: Cannot convert python object to tuple[title: string, url: string] [Exception]
Error: execution of an external program failed: 'src\src\util\nu.exe '
```
Printing in `nimpy.nim` function `pyObjToNimTuple`, `echo size` returns `2`. `echo getSize.isNil` however is true. And `echo getSize(o)` returns `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

**Comment by drewbitt** [comment]
This does work with object instead of tuple. However, I would expect tuple to work here with how similar it is to object (didn't really want to give this its own type)

**Comment by yglukhov** [comment]
Python dicts are pretty far from nim tuples imo. Nim tuples are structural types, ordered, and the fields can be anonymous, e.g. `(string, string)` is a tuple type which is equivalent of `tuple[title: string, url: string]`. Python dicts are better mapped to `JsonNode` if they are json-compatible, or objects if they always provide the fields, or just `PyObject` to skip marshalling and work with the underlying object directly.
