### ISSUE TITLE
Python completion ?

### ISSUE THREAD

**Issue by melMass** [yglukhov/nimpy#136]
I think it's quite related to #115, but I was wondering if there is a way to add stubs in nim to check for the python in nim uses at build time. Ideally, we would have #115 and simply create similar types in Nim and cast to it but maybe there is another cheat to use for now :)

Do you already plan/know when to implement #115?

Thanks

**Comment by melMass** [comment]
Here is what I have blindly tested for now, but the **cast** crash the program

```nim
import nimpy
import strformat

proc isNuke*():bool {.exportpy.} = 
  try:
    let nuke = pyImport("nuke")
    return true
  except Exception:
    return false

type
  Nodes* = PyObject

proc empty*(this:Nodes):bool = 
  var nodes = cast[seq[PyObject]](this) # <= This crashes :(
  if nodes.len == 0:
    return true
  return false

proc selectedNodes*():seq[string] {.exportpy.} = 
    if isNuke():
        let nuke = pyImport("nuke")
        let nodes:Nodes = nuke.selectedNodes()
        if nodes.empty():
            echo "You don't have any node selected"


```

**Comment by melMass** [comment]
Could this be done using the `{.importc.}` pragma in some way just to create an interface ?

**Comment by yglukhov** [comment]
Meh, I don't think you need any of #115. Just work with the `PyObject` as you would do it in python. I.e. how would you implement `empty()` in python?

**Comment by melMass** [comment]
That’s just a simple example I just would like to have my Nuke Node (Python) object to be mapped to a nim type, so that the compiler detects errors or allow code completion from the nim side, the idea is just to get informations from the fields of the Nuke Node Python Object inside nim

**Comment by yglukhov** [comment]
Ah ok. I don't have any plans to implement making-typed-wrappers-for-python-libs. But thats something that could be done on top of nimpy, in a separate lib ;)
