### ISSUE TITLE
Weird behaviour when passing object from Python to Nim?

### ISSUE THREAD

**Issue by matkuki** [yglukhov/nimpy#138]
Hi,

I have a `nimpy` proc that does nothing:
```nim
# nim_lexers.py
proc python_style_test*(start_pos: int,
                        end_pos: int,
                        lexer: PyObject, # <-- This object gets changed/scrambled somehow!
                        editor: PyObject,) {.exportpy.} = # <-- This object gets changed/scrambled somehow!
    echo "HERE"
```
In Python it's called like so:
```python
# Python code snippet
class CustomPythonLexer(data.QsciLexerPython):
  ...
  def styleText(self, start, end):
    nim_lexers.python_style_test(start, end, self, self.editor)
```
When the  first instance of `CustomPythonLexer` class is created and it calls `styleText`, it works perfectly. But when the first `CustomPythonLexer` instance is destroyed and a second is created and takes it's place, something strange happens to the `lexer`  and `editor` arguments, as my whole application starts to behave weird (fonts and styles change for no apparent reason).
If the `lexer` and `editor` parameters are removed, like so:
```nim
# nim_lexers.py
proc python_style_test*(start_pos: int,
                        end_pos: int) {.exportpy.} =
    echo "HERE"
```
then the application works correctly, even when new instances of `CustomPythonLexer` are created.

I have no idea what is happening.
Am I missing something or is something happening to the passed `PyObject` arguments?

Thanks

**Comment by yglukhov** [comment]
I don't see any misuse here. Unfortunately I can't do much without a reproducible sample. Could you make one please?

**Comment by matkuki** [comment]
After trying to cobble together a small example from my larger application, I found that it's not a `nimpy` issue, but a `PyQt5` issue.
Sorry for the false report.
