### ISSUE TITLE
Python 3 not found on Mac OS

### ISSUE THREAD

**Issue by jfilby** [yglukhov/nimpy#144]
When I try import a non-standard module I get an error. However when I import os it works fine.

When I run the following code:

let pysys = pyImport("sys")
echo pysys.version

It looks like nimpy is using Python 2 instead of Python 3. How can I point it to Python 3? I'm using a virtual environment to setup Python 3.

I found a similar issue: https://github.com/yglukhov/nimpy/issues/46

**Comment by yglukhov** [comment]
You can use `pyInitLibPath("/path/to/python.so")` for that.

**Comment by jfilby** [comment]
Is pyInitLibPath() new? I installed Nimpy using nimble but when I try to compile I get:
Error: undeclared identifier: 'pyInitLibPath'

Also, do you know the actual name of the library? I don't have a python.so file on my system (Mac OS).

**Comment by jfilby** [comment]
I used the latest code and pyInitLib was found, but didn't help. But then I am pointing it at the python binary and not any .so file. What sort of library am I looking for on Mac OS?

**Comment by jfilby** [comment]
It worked with the latest code, thanks, I just pointed pyInitLibPath to the python 3 binary in my virtual env.

**Comment by drewbitt** [comment]
@yglukhov why is this necessary for MacOS but not for windows? Code runs fine on Windows without specifying the path but doesn't on MacOS for me as well.

```
python -c 'import sys; print(sys.path)'
['', '/Users/drewbitt/.pyenv/versions/3.8.2/lib/python38.zip', '/Users/drewbitt/.pyenv/versions/3.8.2/lib/python3.8', '/Users/drewbitt/.pyenv/versions/3.8.2/lib/python3.8/lib-dynload', '/Users/drewbitt/.pyenv/versions/3.8.2/lib/python3.8/site-packages']
```

In nimpy:
```
['/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Users/drewbitt/Documents/Github/wn-reading-list-backend/src/util']
```
which is the system python

**Comment by drewbitt** [comment]
It looks like [you load the first libpython*dylib you find](https://github.com/yglukhov/nimpy/blob/42441547ed3d0d31c6b60170222b369de7ffa00a/nimpy/py_lib.nim#L382). Can we get the ability to specify what version we want then?

**Comment by drewbitt** [comment]
Actually, that wouldn't help here since it is completely not finding any python3 dylibs.

**Comment by singularperturbation** [comment]
If you're using pyenv on Mac OS, make sure that you have `PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install <VERSION>` to get it built with a dynamic library, otherwise I don't think that this will work (because it will only have a static library to load).

(found this from https://github.com/JuliaPy/PyCall.jl/issues/122)

**Comment by timotheecour** [comment]
workaround: use `find_libpython` see https://github.com/yglukhov/nimpy/issues/171
