### ISSUE TITLE
Document how to expose custom Nim types

### ISSUE THREAD

**Issue by rominf** [yglukhov/nimpy#149]
I'm working on a graph database based on Nim LMDB bindings. The problem is that it works slower than Python analog because of the Nim JSON module slowness. :( I wanted to try packedjson, but I need to expose `packedjson.JsonNode` as Python `dict`. As it's a non-standard module, I doubt that it should be placed in nimpy. Could you document how to extend nimpy conversion?

**Comment by yglukhov** [comment]
Exporting nim objects as python and methods is currently not possible. As a workaround, you can export just functions. And make use of the fact that nim `ref objects` are generally cheap to pass around python, as they are wrapped into capsules under the hood.
```nim
type MyObject = ref object
  data: int

proc newMyObject(): MyObject {.exportpy.} =
  MyObject(data: 5)

proc getData(o: MyObject): int {.exportpy.} =
  o.data
```
