### ISSUE TITLE
nimpy cannot be used in generic procs

### ISSUE THREAD

**Issue by mratsim** [yglukhov/nimpy#153]
Due to limitation of the upstream semcheck and early symbol resolution, you cannot call a wrapped function in generic proc.

See https://forum.nim-lang.org/t/6321#38994

**Comment by yglukhov** [comment]
Ok, but the workaround is trivial, no? Just use `nimpy.callMethod` directly instead of the `.()` magic.

**Comment by mratsim** [comment]
It's not in the README ;)

**Comment by yglukhov** [comment]
I don't think this particular problem should be in the readme. It's not a nimpy issue after all. Though it could be mentioned in `callMethod` documentation, which doesn't exist, PRs are welcome :)
