### ISSUE TITLE
How to handle py object return types correctly?

### ISSUE THREAD

**Issue by Inky-developer** [yglukhov/nimpy#154]
First of all, sorry if I am missing anything, but I could not find an example how to handle py object as a return type in nim methods.

This is code that works, but I don't think it should be used this way:

```nim
proc getImage(name: string): PyObject {.exportpy.} = 
    let Image = pyImport("PIL.Image")
    
    try:
        Image.open(name)
    except OSError:
        PyObject(rawPyObj: newPyNone())
```

Is this the correct way to construct a pyNone pyObject?

**Comment by yglukhov** [comment]
nil should just work. Doesn't it?

**Comment by Inky-developer** [comment]
Well, that was simple. Thanks for your help :)
