### ISSUE TITLE
Python decorators as Nim pragmas

### ISSUE THREAD

**Issue by Technisha** [yglukhov/nimpy#156]
Heya, since the Nim discord server said that Pragma's are basically a drop-in for Python's decorators, i was wondering if it'd be possible for you to allow people to use Python decorators defined from a python library as a pragma, thanks!

**Comment by yglukhov** [comment]
I don't see how it can work. Here's a python decorator:
```py
def foo():
  pass
foo = myDecorator(foo)
```
Now in nim:
```nim
let myDecorator = ... load it from python
var foo = proc() =
  discard
foo = myDecorator(foo) # What type does `myDecorator` return?
```
Technically python decorators can return any object. E.g. functions of different arity, arg types, return types, etc. There's no way to know it on the nim side, unless you somehow specify the type along with the pragma, but at this point it gets so cumbersome, that calling `myDecorator` manually from nim is not that hard at all.
