### ISSUE TITLE
nimpy.SslError: Unexpected error encountered: SSL Certificate check failed

### ISSUE THREAD

**Issue by z3dc0ps** [yglukhov/nimpy#160]
Traceback (most recent call last):
  File "test1.py", line 6, in <module>
    r=requests.head("http://dev-on-business.nokia.com")
nimpy.SslError: Unexpected error encountered: SSL Certificate check failed.
![1](https://user-images.githubusercontent.com/61974788/85925448-23a81c80-b8b6-11ea-9f0e-1479a11941b7.JPG)
![2](https://user-images.githubusercontent.com/61974788/85925453-26a30d00-b8b6-11ea-8f1e-a1a4cab62e1f.JPG)

**Comment by yglukhov** [comment]
Not a nimpy issue. Could be https://github.com/juancarlospaco/faster-than-requests
