### ISSUE TITLE
Error: unhandled exception: Could not load libpython. python.exe not found. [Exception]

### ISSUE THREAD

**Issue by retsyo** [yglukhov/nimpy#162]
I put the question on the very end of the issues report. And the question is labeled as stong and underline style

# step 1, build pyd as the `README.md`( from https://github.com/yglukhov/nimpy) says 
```nim
# mymodule.nim - which I put in R:\test
import nimpy

proc greet(name: string): string {.exportpy.} =
  return "Hello, " & name & "!"
```

```bash
# Compile on Windows:
nim c --threads:on --app:lib --out:mymodule.pyd mymodule 
```

# make `main.py` to test `mymodule.pyd`
```python
# main.py
import sys
print(sys.path)

import mymodule
print(mymodule.greet("world"))
```

# build EXE file with [pyinstaller](https://github.com/pyinstaller/pyinstaller)
```
pyinstaller.exe main.py
```

now we have the `EXE` file and other`pyd/dll` under `R:\test\dist\main`. The `main.exe` can run under windows without python installation. 

# I try to reuse the self-containd pyinstaller-released main.exe and its accompanying files

```python
# main_nim.nim
import os
putEnv("PYTHONPATH", getAppDir() & ";" & joinPath(getAppDir(), "base_library.zip"))
putEnv("PATH", getAppDir())

echo "PYTHONPATH = ", getEnv("PYTHONPATH", getAppDir() & ";" & joinPath(getAppDir(), "base_library.zip"))

import nimpy

let sys = pyImport("sys")

#~ echo sys.path.to(string)

let mymodule = pyImport("mymodule")
echo mymodule.greet("world")
```

Then I compiled and put main_nim.exe to `R:\test\dist\main`
and I have to copy files( contextlib.py, genericpath.py, ntpath.py, os.py, site.py, stat.py, sysconfig.py, token.py, tokenize.py, _sitebuiltins.py) and directory 'importlib' from `python\lib`. 

Then
```
R:\test\dist\main>main_nim.exe
PYTHONPATH = R:\test\dist\main;R:\test\dist\main\base_library.zip
R:\test\main_nim.nim(7)  main_nim
C:\Users\USER\.nimble\pkgs\nimpy-0.1.0\nimpy.nim(1279) pyImport
C:\Users\USER\.nimble\pkgs\nimpy-0.1.0\nimpy\py_lib.nim(519) initPyLibIfNeeded
C:\Users\USER\.nimble\pkgs\nimpy-0.1.0\nimpy\py_lib.nim(481) initPyThreadFrame
C:\Users\USER\.nimble\pkgs\nimpy-0.1.0\nimpy\py_lib.nim(373) pythonLibHandleFromExternalLib
Error: unhandled exception: Could not load libpython. python.exe not found. [Exception]
```

<u>**which can be fixed easily**</u>: just copy any file( even a file with 0 byte) to python.exe, and put it live with main_nim.exe

```
R:\test\dist\main>main_nim.exe
PYTHONPATH = R:\test\dist\main;R:\test\dist\main\base_library.zip
Hello, world!
```

what we can know from this that "python.exe" is not really need in this situation. 

<u>**So can you move this limitation and let nimpy does not search `Python.exe`?**</u>  Thanks.

**Comment by retsyo** [comment]
I made a quick-and-dirty change in `py_lib.nim`. Then the problem I addressed above has gone.

change
```python
proc pythonLibHandleFromExternalLib(): LibHandle {.inline.} =
  when defined(windows):
    let pythonExe = findExe("python.exe")
    if pythonExe.len != 0:
      let d = parentDir(pythonExe)
      for lib in libPythonNames():
        result = loadLib(d / lib & ".dll", true)
        if not result.isNil:
          break

      if result.isNil:
        let s = toSeq(libPythonNames()).mapIt(d / it & ".dll").join(", ")
        raise newException(Exception, "Could not load libpython. Tried " & s)
    else:
      raise newException(Exception, "Could not load libpython. python.exe not found.")
  else:
    # Try this process first...
    result = loadLib()
```

to
```python
proc pythonLibHandleFromExternalLib(): LibHandle {.inline.} =
  #~ when defined(windows):
    #~ let pythonExe = findExe("python.exe")
    #~ if pythonExe.len != 0:
      #~ let d = parentDir(pythonExe)
      #~ for lib in libPythonNames():
        #~ result = loadLib(d / lib & ".dll", true)
        #~ if not result.isNil:
          #~ break

      #~ if result.isNil:
        #~ let s = toSeq(libPythonNames()).mapIt(d / it & ".dll").join(", ")
        #~ raise newException(Exception, "Could not load libpython. Tried " & s)
    #~ else:
      #~ raise newException(Exception, "Could not load libpython. python.exe not found.")
  if true: #else:
    # Try this process first...
    result = loadLib()
```

**Comment by yglukhov** [comment]
Sounds like `pyInitLibPath` is the solution, no?

**Comment by yglukhov** [comment]
No response, closing. Please reply if `pyInitLibPath` doesn't work.

**Comment by retsyo** [comment]
just call `pyInitLibPath` before `import nimpy`, which can fix the problem
```
import nimpy / py_lib
pyInitLibPath(os.getAppDir() / "python36.dll")

import nimpy
```

**Comment by AkmDgreat** [comment]
@yglukhov @retsyo `pyInitLibPath(os.getAppDir() / "python36.dll")` works for a windows machine, but not on MacBook, because `.dll` files only exist on Windows.

So, I tried `pyInitLibPath(os.getAppDir() / "python36.dll")`, but it does not work. I also tried `pyInitLibPath("/Users/akmdgreat/anaconda3/lib/libpython3.11.dylib")`, but that does not work either. In both the cases, I get an error: `Error: unhandled exception: Could not load libpython. Tried /Users/akmdgreat/anaconda3/lib/libpython3.11.dylib [ValueError]`


Some info about where Python was installed:
```python
from distutils.sysconfig import get_config_var

print(get_config_var("LIBDIR"))
# /Users/akmdgreat/anaconda3/lib

print(get_config_var("LDLIBRARY"))
# libpython3.11.a
```
Also, in the `/Users/akmdgreat/anaconda3/lib` directory, there's a file  `libpython3.11.dylib`

**Comment by yglukhov** [comment]
@AkmDgreat If the dylib is there but could not be loaded, could it be an architecture mismatch? E.g. libpython is arm, and your executable is amd64?

**Comment by bridgeQiao** [comment]
> @AkmDgreat If the dylib is there but could not be loaded, could it be an architecture mismatch? E.g. libpython is arm, and your executable is amd64?

It's true. I have encountered the same issue. Actually, my Nimble's CPU type is x86_64. It's strange, and I've decided to try using choosenim to reinstall it.

```bash
otool -hv ~/.nimble/bin/nimble
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   X86_64        ALL  0x00     EXECUTE    17       1776   NOUNDEFS DYLDLINK TWOLEVEL PIE
```

**Comment by bridgeQiao** [comment]
I found that the problem lies with choosenim. My mac is M2, the init script downloads an x86_64 executable by default.
https://github.com/dom96/choosenim/blob/master/scripts/choosenim-unix-init.sh#L127
> # TODO: We don't have arm binaries for choosenim so far, rely on Rosetta.
