### ISSUE TITLE
PyObject, check if boolean and if None

### ISSUE THREAD

**Issue by ggonnella** [yglukhov/nimpy#164]
Is there in the API a way to check if a PyObject is of type Py_Bool (i.e. if it is one of Py_True or Py_False)?
And to check if a PyObject is Py_None?

**Comment by ggonnella** [comment]
PS: my current solution is:

```nim
let
  builtins = pyBuiltinsModule()
  PyTrue = builtins.True
  PyBoolClass = builtins.True.getattr("__class__")
  PyNoneClass = builtins.None.getattr("__class__")

proc is_bool*(py: PyObject): bool {.exportpy.} =
  return builtins.isinstance(py, PyBoolClass).to(bool)

proc is_none*(py: PyObject): bool {.exportpy.} =
  return builtins.isinstance(py, PyNoneClass).to(bool)
```
Although working correctly I don't find it very elegant and probably it's also not very efficient.

**Comment by ggonnella** [comment]
For me the issue is set, since it was related to the to_json inability to convert correctly to JNull and JBool nodes. However methods such as those mentioned above (but written using the internals instead) could be useful in the API for allowing writing generic Nim code accepting different datatypes from Python (such as done in the to_json proc).

**Comment by ggonnella** [comment]
#167 addresses this

**Comment by yglukhov** [comment]
Sorry, I doubt it should be in nimpy. There should be enough low-level primitives in `py_lib.nim` to implement this api elsewhere. Besides, I'm considering mapping python `None` to `PyObject(nil)` in future, so `isNil` will just work.

PS Sorry for wasting your time by not responding timely.

**Comment by ggonnella** [comment]
ok. don't worry.
