### ISSUE TITLE
"could not load pcre64.dll"

### ISSUE THREAD

**Issue by Wykleph** [yglukhov/nimpy#169]
I am trying to use `re` module and compiling to a `pyd`.  I have verified that the dll file exists in the `nim/bin` folder, the `nim/bin` folder is in my `PATH`, I have 64 bit python and 64 bit nim, I have tried using new `pcre64.dll` file and I'm still having issues.  I have even placed the `pcre64.dll` file into the same directory and that doesn't seem to work.  I was able to compile this just a few days ago, but I have verified that everything is 64 bit and it still cannot load the file.  Here is the nim code I'm using:

```nim
    import re
    import random
    import nimpy
    import strutils
    randomize()

    let spintax_bracket: Regex = re(r"(?<!\\)((?:\\{2})*)\{([^}{}]+)(?<!\\)((?:\\{2})*)\}")

    proc random_pick(text: string, full_text: string): string {.exportpy.} =
        let replacement = text[1 .. text.high - 1].split("|").sample()    
        return full_text.replace(text, replacement)

    proc spin(text: string): string {.exportpy.} = 
        var new_string: string = text
        while true:
            let matches: seq[string] = findAll(new_string, spintax_bracket)
            if matches == @[]: break
            for m in matches:
                new_string = random_pick(m, new_string)
        return new_string
```

Compiling with command:

`nim c --app:lib --out:spinim.pyd spinim`

Python code below:

```python
    from time import time
    import spinim

    start = time()
    for i in range(1000):
        e = spinim.spin("{Hey|Hello|Hi} this is {spin syntax|spintax}{.|!|}")
    end = time()
    print(f"Finished in {end - start}")
    print(e)
```

Would it be possible to add the ability to specify where missing dll files can be located?

**Comment by yglukhov** [comment]
I don't remember how dlls are searched on windows, but it might be that the search path is either some global ($WINDIR\system32?) or the directory with the executable, which is python.exe in your case i suppose. Apart from that I don't think nimpy (or nim even) is related to this issue.

**Comment by Sann0** [comment]
Since this is the only issue I've found to this topic: Is there a way to ship nimpy projects without shipping the `pcre64.dll` aswell?

**Comment by yglukhov** [comment]
> Is there a way to ship nimpy libraries without shipping the pcre64.dll aswell?

Yes. Don't use pcre in your library. Nimpy itself doesn't depend on pcre.

**Comment by Wykleph** [comment]
> > Is there a way to ship nimpy libraries without shipping the pcre64.dll aswell?
> 
> Yes. Don't use pcre in your library. Nimpy itself doesn't depend on pcre.

I'm new to Nim so maybe I'm missing something, but that seems like a design flaw in Nimpy if it cannot handle libraries that it doesn't explicitly depend on.  Why can't Nimpy use libraries it doesn't depend on?  If I have external libraries my project needs I should be able to tell Nimpy about them, no?

**Comment by yglukhov** [comment]
Well nimpy is not at the level to do anything about DLL dependencies, those are always a PITA. Ideally nim library (re) in our case should expose an interface to tweak its dll search path. Or maybe some `--dynlibOverride` magic could help here, but there's no one silver bullet. Though if you see a way for nimpy to improve in these regards, you're welcome to share your ideas, ideally in the form of a pull request.

**Comment by Wykleph** [comment]
I just don't know enough to be useful I don't think.  I mostly use non-compiled languages like python and I don't even know what would need to be considered for a fix like that.  I do think it would be a useful feature though.

**Comment by Sann0** [comment]
As mentioned before, nimpy itself doesn't depend on `pcre` so the best solution on the users end would be to switch to https://github.com/nitely/nim-regex - that's at least what I did.

**Comment by yglukhov** [comment]
Indeed. Feel free to offer any ideas of how nimpy can improve. Otherwise I have none.
