### ISSUE TITLE
Object contianing ordinals enum cannot be passed as Nimpy parameters

### ISSUE THREAD

**Issue by Clonkk** [yglukhov/nimpy#170]
The following 
```nim
type
  MyEnum = enum
    E1, E2, E3
  Type1 = object
    e: MyEnum
```

`Type1` cannot be passed as a parameter for the function `callMethod` despite the enum object being ordinals and convertible to integer.

If I replace e with an integer it works.

Shouldn't Ordinals Enum be passable as an int value to Nimpy since it is JSON Serializable ?

**Comment by Vindaar** [comment]
It's not a matter of being JSON serializable (remember, nimpy interfaces directly with Python's C API), but rather that it's unclear how to handle it in a general case. 

If you want Python to see it as an integer in the first place, you can do the conversion on the Nim side. If enums are to be special, what should they map to given that Python doesn't support enums natively? 
Note: just checked and apparently there's a Python stdlib module for enum support, but that seems more of an emulation on top of normal Python objects. Not sure I'd call that a good fit.

What use case do you have in mind?

**Comment by Clonkk** [comment]
Actually, I don't know why I assumed passing object from Nim to python would call JSON serialization; I got confused I guess, my bad :)

My use case is a bit complex;
So I'll try to explain it as best as I can, just ask if I'm not clear :)
 
I want to have Nim managing parameters value used to call a python hook I will have something like this : 
```nim
type
  MyEnum* = enum
    E1, E2
  Params* = object
    param1*:  int
    param2*:  bool
    param3*:  float
    param4*: MyEnum

proc paramsHandler(p: ref Params)=
#Do stuff...

proc callPythonHook(params: Params, data: seq[float64])=
  var res = nimpy.callMethod(myModule, "funcname", params, data)
  # Do Python scripting stuff.
```
I use a serialized `Table[string, float] ` (obtainted through a socket) to update Params value when needed. 
Params value will probably expand in the future (possible values will stay Ordinals). Therefore, I decided use fieldPairs to iterate through `Params` and update field value when its name is in the table. If there is no value in the table, the current value is kept.
I call a generic function setField[T] to update the value from a float with generic type conversion

```nim
proc setField[T](field: var T, value: float64) =
  field = value.T

proc updateParams(args: var Params, tab: var Table[string, float64]) =
  # Copy tuple to modify it
  for name, field in args.fieldPairs:
    var value: float64 = 0.0
    if tab.pop(name, value):
      setField(field, value)
      info("[Dapo] ", name, " Updated to ", field)
```

The idea is that param4 is an enum (its possible values are limited). I want to pass Params to nimpy.callMethod and in Python it will be treated as a dictionnary. But since Enum value do not get converted to integer, It fails to compile. But `MyEnum` is an ordinal enum that should be convertible to int (since Ordinals enum are C-compatible).

With `param4` as an `int` , `setField` convert a `float` value to `int` value and it doesn't check if the value contained in `tab["param4"]` is a valid MyEnum value. So If I have an invalid error in my table, it may go undetected.

If `param4` is of the type `MyEnum` the conversion float -> enum will detect errors.

And the only thing preventing from using MyEnum is that I want to pass it to `nimpy.callMethod`
If Ordinals enum could be treated as integer when going through the C-Python API it would solve the problem :).

There are possible workaround with adding boilerplate code or handling the Enum field in a non-generic way but I would like to avoid it if possible

**Comment by Vindaar** [comment]
Hmm, I see the problem. 

If we were to decide to definitely not support enums, one could restrict the generic of `nimValueToPy`. That would allow the user to define a converter for the enum, which would be called automatically. So changing it to:
```nim
proc nimValueToPy[T: not enum](v: T): PPyObject {.inline.}
```
allows the following to work:
```nim
import nimpy
type
  MyEnum = enum
    m1, m2, m3, m4

converter toInt(x: MyEnum): int = x.int

let a = m1
let py = pyBuiltinsModule()
echo py.callMethod("type", a)
# prints: <class 'int'>
```

Another, but a bit more hacky approach is to allow to user extend the `nimValueToPy` proc by checking for a user defined helper. This can be done by using `declared` (which probably breaks under some circumstances). Replace the last `else` branch in that proc by:
```nim
  else:
    when declared(makePyConvertable):
      nimValueToPy(makePyConvertable(v))
    else:
      unknownTypeCompileError(v)
```
and then defining such a proc, in our example, which replaces the converter:
```nim
import nimpy
type
  MyEnum = enum
    m1, m2, m3, m4

proc makePyConvertable(x: MyEnum): int = x.int

let a = m1
let py = pyBuiltinsModule()
echo py.callMethod("type", a)
```

As I said, a bit hacky but that's what makes it fun. ;) 

In any case, from the top of my head I can't think of a good way to make your code work with minimal changes. I think @yglukhov should chime in about how one should handle it.

**Comment by Clonkk** [comment]
Modifying  `nimValueToPy` to handle enum using their ordinal value seems simple enough and handle this use case.
The only issues with handling this way is that enum that are actually not consecutive ordinal may still have invalid values as the conversion to enum is a range check, so if your value is "hole" in your enum the conversion will still compile.

I opened a PR with my proposed modification, we can discuss around the code.
