### ISSUE TITLE
don't raise `Exception`, raise `AssertionDefect` or `NimpyError` (inheriting from `CatchableError`) or call `raisePythonError`

### ISSUE THREAD

**Issue by timotheecour** [yglukhov/nimpy#174]
raising `Exception` directly seems bad, instead we should distinguish recoverable vs non recoverable errors, eg:

* `raise newException(Exception, "Can not stringify exception")`
=> `raise newException(AssertionError, "Can not stringify exception")` 

* `raise newException(Exception, "No callable attribute: " & $name)`
=> is this correct or should `raisePythonError` be used here?

**Comment by timotheecour** [comment]
@yglukhov why not `PythonError` instead? with `PythonError` a subclass of CatchableError or some other of its subclasses; this would make it easier for user code to handle those specifically

**Comment by yglukhov** [comment]
No opinion really, just an arbitrary pick.
