### ISSUE TITLE
Cannot Call Pure Function From Multiple Threads

### ISSUE THREAD

**Issue by Pebaz** [yglukhov/nimpy#179]
Hello, I'm the author of [Nimporter](https://github.com/Pebaz/Nimporter) and I'm trying to debug a multithreading issue (as described [here](https://github.com/Pebaz/nimporter/issues/19) for completeness but also happens without using Nimporter).

Put simply, calling any Nim function in another thread causes Python to crash.

### Reproduction Steps

calc.nim:
```nim
import nimpy

proc add(a: int, b: int): int {.exportpy.} =
    return a + b
```

Compiled with: `nim c --threads:on --app:lib --out:calc.pyd calc`

Import and use in Python file:
```python
import threading, calc

def foo():
    print(calc.add(1, 2))

threading.Thread(target=calc).start()  # Crashes Python
```

Starting the second thread is what causes the crash.

**Comment by yglukhov** [comment]
Just ran it on linux, and it doesn't crash. There seems to be a typo in your code `target=calc` which causes python exception
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'module' object is not callable
```
But if corrected, the program runs just fine. So it might be something windows specific.

**Comment by Pebaz** [comment]
Ah, yes sorry for the copy paste error.
That sounds familiar, now that you say that it works on Linux, I believe that there may be a Nim flag I can set for this.
Thanks for looking into it!
