### ISSUE TITLE
Raise equivalent Nim-Exception

### ISSUE THREAD

**Issue by tim-st** [yglukhov/nimpy#18]
It would be helpful to have the equivalent nim exception raised like the python one if there is an equivalent (like IOError, ValueError,...) and fallback to a generic Exception.
I saw the Exception type is also delivered from the python side (`raise newException(Exception, typns & ": " & valns)`, `typns` here) so that would be possible with a small case, but of course low prio.

**Comment by kdheepak** [comment]
I wanted to bump this thread. This would be extremely useful for writing elegant Nim code.
