### ISSUE TITLE
nimble error

### ISSUE THREAD

**Issue by GaudiestTooth17** [yglukhov/nimpy#181]
When I run the command `nimble install nimpy` I get the following output:
`Downloading https://github.com/yglukhov/nimpy using git
       Info Hint: used config file '/etc/nim.cfg' [Conf]
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /tmp/nimble_9965/githubcom_yglukhovnimpy/nimpy.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     usr/lib/nim/pure/times.nim(79, 9) Error: cannot 'importc' variable at compile time.`

I'm running Ubuntu 18.04.

**Comment by yglukhov** [comment]
What's you nim and nimble version?

**Comment by GaudiestTooth17** [comment]
nim version is 0.17.2 and nimble version 0.8.8

**Comment by yglukhov** [comment]
A version that old is not really expected to work. Please try something more recent. Latest LTS version is 1.2.* iirc.

**Comment by GaudiestTooth17** [comment]
This probably isn't the right place to ask this, but when I try updating nimble with `nimble install nimble` I get this error: `Downloading https://github.com/nim-lang/nimble using git
  Verifying dependencies for nimble@0.12.0
 Installing nimble@0.12.0
   Building nimble/nimble using c backend
    Prompt: Build failed for 'nimble@0.12.0', would you like to try installing 'nimble@#head' (latest unstable)? [y/N]
    Answer: n
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Aborting installation due to build failure`
I've even tried installing the the latest unstable version, but it also won't build. I'm brand new to nim, so I'm still getting things figured out. Your help is really appreciated!

**Comment by yglukhov** [comment]
I'd suggest removing nim and nimble altogether through apt if that's how you installed it in the first place. And then use choosenim.

**Comment by GaudiestTooth17** [comment]
That fixed my problems! Thank you again so much.
