### ISSUE TITLE
--app:gui says "Error: unhandled exception: index -1 not in o ..9793[IndexDefect]"

### ISSUE THREAD

**Issue by retsyo** [yglukhov/nimpy#182]
for the following simple code `bug.nim`
```
import os

import nimpy
let sys = pyImport("sys")

echo "sys.path = ", sys.path
```

if I compile it with `nim c --o:bug_cli bug.nim` and copy `bug_cli.exe` to the directory where `python.exe` and `python36.dll` live, `bug_cli.exe` can run as expected

however, if I compile it with `nim c --o:bug_gui --app:gui bug.nim` and copy `bug_gui.exe` to the directory where `python.exe` and `python36.dll` live, when I run `bug_gui.exe`, I get

![bug](https://user-images.githubusercontent.com/7960913/102762206-edee7700-43b2-11eb-960d-50bc6767571c.jpg)

so, what is the problem?

**Comment by yglukhov** [comment]
Can not reproduce. The program runs fine with no output. Are you sure this is nimpy issue? The stack trace doesn't necessarily imply it.

**Comment by retsyo** [comment]
not sure
but this disappears with 
```
$ nim
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-01-25
Copyright (c) 2006-2021 by Andreas Rumpf
```
