### ISSUE TITLE
nimble cannot import nimpy on OpenBSD

### ISSUE THREAD

**Issue by since19861019** [yglukhov/nimpy#183]
nimpy.nimble imports os ( and strutils ) though they are not used.

On OpenBSD ( OpenBSD 6.8. nim 1.2), os.nim invokes getFilePermission, which is not available in NimScript.
As os ( and strutils ) is not used in the nimble file, the import should be removed.

**Comment by yglukhov** [comment]
> though they are not used

Actually they are used for the makeshift test runner.

> On OpenBSD ( OpenBSD 6.8. nim 1.2), os.nim invokes getFilePermission, which is not available in NimScript.

This sounds like a nim issue, and should be easy to fix

**Comment by since19861019** [comment]
It seems that I have to wait for OpenBSD to update the nim version in future release in order to use nimble.
Until then, I will use nimpy source files directly in my project folders.

**Comment by yglukhov** [comment]
Guess it can be closed then
