### ISSUE TITLE
No code execution of exported functions in python threads

### ISSUE THREAD

**Issue by qb-0** [yglukhov/nimpy#189]
Not sure if that's a nimpy issue at all but I've noticed that exported nimpy functions can't be used in python threads. Also there won't be any python code execution after I've tried to run a nimpy function in a python thread.

`nim c --threads:on --app:lib --out:bridge.pyd bridge.nim`
```nim
import nimpy
proc add(a, b: int): int {.exportpy.} = a + b
```

```python
import bridge, threading

def foo(a, b):
    print(bridge.add(a, b))

print(bridge.add(200, 200))
t = threading.Thread(target=foo, args=(50, 50))
t.start()
t.join()
print("No execution here")
```

**Comment by yglukhov** [comment]
Works for me on linux. Will take some time to test it on windows.

**Comment by yglukhov** [comment]
Ok it seems tls emulation is getting in the way, and it seems like nim doesn't support foreign threads with tls emulation, correct me if i'm wrong.

**Comment by Sann0** [comment]
I don't want to reopen that issue because disabling tls emulation indeed fixes the example mentioned above, but it breaks my current Project. I would be surprised if you know that answer for that issue, but do you got any advices what I could check further?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing: The specified module could not be found.
```

It seems like it doesn't gets recognized as an extension anymore.

`python -v` with `tlsEmulation` disabled
```
>>> import module
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing: The specified module could not be found.
```

`python -v` with `tlsEmulation` enabled
```
# extension module 'modulename' loaded from 'path'
# extension module 'modulename' executed from 'path'
import 'modulename' # <_frozen_importlib_external.ExtensionFileLoader object at 0x0000016554B81280>
```

**Comment by yglukhov** [comment]
Not sure whats going on here tbh. Can you reduce it to a reproducible sample?

**Comment by Sann0** [comment]
Indeed I was. Compiling it with `--threads:on` in combination with `--tlsEmulation:off` makes it not importable anymore. I didn't recognized that I wasn't using `--threads:on` before. What is exactly the reason why nimpy modules need the threads flag as it seems to run as expected without `--threads:on`?

**Comment by yglukhov** [comment]
> Same for the example above

Nope. Works perfectly for me. Are you sure you haven't messed up module names? By default both your **main nim file** and the compiled .pyd file should be named after the module you're importing.

> What is exactly the reason why nimpy modules need the threads flag as it seems to run like expected without `--threads:on`

They need it in order to work correctly when called from multiple threads. If your program only has one thread, compiling without threads support is fine.

**Comment by Sann0** [comment]
> Nope. Works perfectly for me. Are you sure you haven't messed up module names? By default both your **main nim file** and the compiled .pyd file should be named after the module you're importing.

Weird. For me it's reproducible:
![alt text](https://i.imgur.com/oY1AmJu.gif)

> They need it in order to work correctly when called from multiple threads. If your program only has one thread, compiling without threads support is fine.

So if I'm calling functions from my nimpy module with python threads, then `--threads:on` would be required right?

**Comment by yglukhov** [comment]
> Weird

Indeed. I'm running the same configuration, and not getting any errors. My python version is 2.7.4 installed from python.org. Can you inspect the resulting binaries for the exported symbols? You should be looking for `initbridge` and `PyInit_bridge`.

> So if I'm calling functions from my nimpy module with python threads, then --threads:on would be required right?

Correct

**Comment by Sann0** [comment]
They're present:
```
    ordinal hint RVA      name

          1    0 00013ED0 NimMain
          2    1 00013AB0 PyInit_bridge
          3    2 00013AA0 initbridge
```

> My python version is 2.7.4
Yep, it's importable with python2. But not on python3 (I'm on 3.8.7)

**Comment by yglukhov** [comment]
Sorry, that was a typo, I'm using python 3.7.4 and it works fine. Tried installing python 3.9.1 but apparently I'm too dumb/lazy to make it appear in cmd, windows is freakin ridiculous. I'll try harder if you confirm that it does work on 3.7.4 and not on a later one.

**Comment by Sann0** [comment]
> I'll try harder if you confirm that it does work on 3.7.4 and not on a later one.

Yes it works on 3.7.4 aswell

**Comment by yglukhov** [comment]
Can you retest it with https://github.com/yglukhov/nimpy/pull/195 please?

**Comment by Sann0** [comment]
> 
> 
> Can you retest it with #195 please?

Seems to make no difference, doesn't works on 3.8 or 3.9

**Comment by yglukhov** [comment]
I've reduced to https://github.com/nim-lang/Nim/issues/16895

**Comment by Sann0** [comment]
Any updates on this? Just read the issue on Nim and seems like noone exactly knows what's going on huh?

**Comment by yglukhov** [comment]
As reported by @cer1969, `--tlsEmulation:off` causes the final binary to depend on `__emutls_get_address` symbol from `libgcc_s_seh-1.dll`.

I don't think nimpy can do anything about it, it's all mostly about link options.

**Comment by jfmontanaro** [comment]
Just wanted to chip in with a workaround for this in case anyone finds it from Google as I did: The issue is specific to the `mingw` toolchain. So if switching C compilers is an option for you, either `--cc:vcc` or `--cc:clang` seems to work fine when compiling with `--threads:on` and `--tlsEmulation:off`.
