### ISSUE TITLE
pyd file on windows has dependency on libgcc_s_seh-1.dll (from mingw64)

### ISSUE THREAD

**Issue by cer1969** [yglukhov/nimpy#203]
Hi:
I have nimpy 0.1.1 and nim 1.4.4.
I have detected that my compiled pyd files have a dependecy on libgcc_s_seh-1.dll (from mingw64 recommended in nim website).
When I copy that file in the same directory of my pyd file everything works ok (even with differents python versions).

Is that ok?
Is posible to avoid that dependency?

**Comment by yglukhov** [comment]
What's the command you're using to build the pyd?

**Comment by cer1969** [comment]
The one indicated on github:
nim c --threads:on --app:lib --tlsEmulation:off --out:mymodule.pyd mymodule

**Comment by yglukhov** [comment]
Does it change without `tlsEmulation` flag?
```
 nim c --threads:on --app:lib --out:mymodule.pyd mymodule
```

Can you see what symbols are being used from `libgcc_s_seh-1.dll`?

**Comment by cer1969** [comment]
Only one symbol: __emutls_get_address (checked with this https://github.com/lucasg/Dependencies).
Without the tlsEmulation flag works ok. The only dependencies are kernel32.dll y MSVCRT.dll.

**Comment by yglukhov** [comment]
I believe it's the same issue as https://github.com/nim-lang/Nim/issues/16895.
Also relevant: #189

**Comment by yglukhov** [comment]
I don't think nimpy can do anything about it, it's all mostly about link options.

**Comment by cer1969** [comment]
I'am ok using the dll (it is just 74 kb), but I'am not sure which option is better.

**Comment by yglukhov** [comment]
There might be a way to statically link to `libgcc_s_seh-1`. Please share your findings if you're into it :)
