### ISSUE TITLE
Python.dll load needs all default libraries?

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [yglukhov/nimpy#204]
Hey,

maybe you have some idea about this. I recently tried executing python code via nimpy after loading python38.dll. The code, which should be executed afterwards was one of the README examples:

`
let os = pyImport("os")
echo "Current dir is: ", os.getcwd().to(string)
` 

However, after python38.dll was loaded, i got the following error:

![image](https://user-images.githubusercontent.com/27858067/112148367-15d1be80-8bde-11eb-8c63-067907620d81.png)

This could only be fixed by copying the whole python38 DLL and Lib folders into the current working directory. I'm wondering why this is needed at all. I would expect, that only the OS library should be needed here. Am I missing something?

Greetings

**Comment by yglukhov** [comment]
I would guess something is wrong with your python installation, internet is full of those errors if you search for it. It might as well be some problems with discovery in nimpy.

**Comment by S3cur3Th1sSh1t** [comment]
I think this error is due to no python installation on the target system in combination with no `PYTHONHOME` and `PYTHONPATH` set. The `Python38.dll` seams to need some default libraries for the initialization, which are not found. 

Did you ever use nimpy binaries on a windows system without python installed?

**Comment by yglukhov** [comment]
> Did you ever use nimpy binaries on a windows system without python installed?

No. Never tested that.

**Comment by S3cur3Th1sSh1t** [comment]
Ok thanks anyway. It’s most likely not nimpy related so I‘m closing it now.
