### ISSUE TITLE
Is there a way to use tuples?

### ISSUE THREAD

**Issue by narimiran** [yglukhov/nimpy#22]
When I try to do something like this:

```nim
proc simpleDifference(a, b: tuple[x, y: float]): tuple[x, y: float] {.exportpy.} =
  result = (a.x - b.x, a.y - b.y)
```

I get:
```
Error: type mismatch: got <tuple[x: float, y: float]>
but expected one of:
proc unknownTypeCompileError()

expression: unknownTypeCompileError(v)
```

What am I doing wrong?  
Can I use Nim's tuples and/or interact with Python's tuples?

**Comment by narimiran** [comment]
Thanks for the quick fix, but I need to re-open this.

Now it works with tuples - if you call the Nim proc **only once**. If you try to call it multiple times, e.g. from the example in tests:
```python
s.tupleDiff((5, 4), (2, 3))
s.tupleDiff((15, 4), (2, 3))
```

you get either this:
```
munmap_chunk(): invalid pointer
No stack traceback available
SIGABRT: Abnormal termination.
```
or if you call it three times:
```
No stack traceback available
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by narimiran** [comment]
I tried to narrow it down a bit, but I couldn't find any meaningful conclusion that holds 100% of time.

It _seems_ that procs which **return** a tuple are **not a problem**.

The problem rises **sometimes** with procs which have a tuple (or more than one tuple) as an argument - sometimes it works even on multiple calls, sometime it fails after a random number of calls (both with the same argument values and with different argument values).

**Comment by yglukhov** [comment]
Should be good now.

**Comment by narimiran** [comment]
> Should be good now.

It seems so.

Thank you once again for your quick fixes! Great customer support! :)
