### ISSUE TITLE
Question: Is it possible to inherit from a python class on the Nim side?

### ISSUE THREAD

**Issue by kobi2187** [yglukhov/nimpy#228]
Is it possible to do inheritance like python's
class MyApp(ParentApp): ...
but from the Nim side? (when all I have is access to ParentApp or an abstract class, and I am supposed to implement the specific child class)
some frameworks require subclassing their classes and implementing some methods, 
which then call the parent's run() function or something similar.

I usually work the other way around, implementing all the logic in Nim, and presenting it to the python side as a .so lib, but wondered if it's possible to "takeover" the main entry point as well. (and then replace python library parts if needed)

Anyway, I couldn't find in the documentation or tests a clear way of doing that. 
Thanks!

**Comment by yglukhov** [comment]
Will  #229 work for you? :)

**Comment by kobi2187** [comment]
:-) may I tell you - that you are awesome? 
very leet!
I will test probably tomorrow if this works for my usecase.
Thanks a lot!

**Comment by kobi2187** [comment]
Nice! so looking at the tests, this is now possible, but not very easy to use. 
can we have something like
pyInherit(MySubClass, ParentClass)
and then I can do things like:
method build(self:MySubClass) = ...
and the python code will call this build function?

**Comment by kobi2187** [comment]
Nice! so looking at the tests, this is now possible, but not very easy to use. 
can we have something like
pyInherit(MySubClass, ParentClass)
and then I can do things like:
method build(self:MySubClass) = ...
and the python code will call this build function?

**Comment by yglukhov** [comment]
Should be doable as a side project. I'm not sure yet about including this in nimpy, as the concept diverges too much from natural nim for not-that-popular use case. Therefore I encourage you to try it yourself ;)

**Comment by kobi2187** [comment]
Thank you, I am not sure I have the time :-/

looking at the python builtin docs I see:
https://docs.python.org/3/library/types.html#dynamic-type-creation
 types.new_class(name, bases=(), kwds=None, exec_body=None)
it can accept a base class, so perhaps simply calling this text in a py.exec call?
hmm, but then how do you add your own nim procs under the correct py class?

**Comment by kobi2187** [comment]
btw, I think it is a needed feature, for when you want to interact with a framework, and still stay on the nim side longer.
right now, I am working with nim functionality lib and minimal python + gui calling that lib for speedy funcs.
I am using python's kivy gui, and it requires such a use case.

**Comment by yglukhov** [comment]
Well the "subclassing" test in nimpy shows that you can totally pull it off on the nim side, even though there's some boilerplate involved. Now what you're asking for is just ergonomics as I understand it. For ergonomics you can play around with macros/templates to wrap the boilerplate, there's nothing in nimpy preventing you from doing that. As for doing it in nimpy, like I said, ergonomics for this particular use case is not a priority at the moment, neither it is a low hanging fruit for me. But I will surely review anyone else's efforts on this front, and will consider adding it to nimpy if the implementation is robust and provides a **natural enough** syntax.

**Comment by kobi2187** [comment]
Yes, I understand and respect your point of view. I may try your solution again, and make it work for me. Thanks man :-)
