### ISSUE TITLE
Map repr to __repr__ and `$` to __str__

### ISSUE THREAD

**Issue by lhupfeldt** [yglukhov/nimpy#231]
It would be great if the following mappings were done:
  repr -> \_\_repr\_\_
  \`$\` -> \_\_str\_\_

**Comment by yglukhov** [comment]
`$` is already mapped to `__str__` iirc. I don't think `repr` should be part of nimpy, you can easily implement one yourself:
```nim
proc repr(o: PyObject): string = pyBuiltinsModule().callMethod(string, "repr", o)
```
