### ISSUE TITLE
Document how to create a Python package implemented in Nim

### ISSUE THREAD

**Issue by lhupfeldt** [yglukhov/nimpy#233]
A small example of how to create a Python package implemented in nim, without exposing the implementation in any way would be great.
I'm thinking about including the generated C code in the package?

This project is awesome!
I got stuck on porting my Python package to Nim because of the amount of work that would be involved in porting my pytest suite, but now I have my hopes up again.

**Comment by yglukhov** [comment]
Thanks for the kind words. However I don't understand the issue. The README already tells how to do it. Otherwise feel free to contribute to the wiki.
