### ISSUE TITLE
Passing enum values to nim via nimpy

### ISSUE THREAD

**Issue by MegaIng** [yglukhov/nimpy#235]
This is the question for the inverse of #170 . I want to interface with a tool written in nim. I am trying to write a wrapper around it that is as small as possible, and nimpy does for the most part allow that. Getting the values out of nim is easy, since everything is easily converted to a python object. However, nimpy refuses to take in Enum values from python code. Is there any workaround? I did not find a way to write a custom converter. The only workaround I find is to duplicate the full data structure in a nimpy compatible way, which I find less than optimal.

Related: Is there a way to make nimpy directly output the string value of the enum instead of their ordinal value? Currently I have a simple wrapper function, but if that can be avoided that would be nice.

**Comment by MegaIng** [comment]
> Please provide a reproducible sample along with actual and expected result

Yeah, sorry should have done that.

```
import nimpy

type SomeEnum = enum
  SE_A
  SE_B
  SE_C

type SomeObject = object
  name: string
  enum_value: SomeEnum

proc parse*(text: string): SomeObject {.exportpy.} =
  SomeObject(name: text, enum_value: SE_A)

proc unparse*(obj: SomeObject): string {.exportpy.} =
  obj.name
```

In the above code the `parse` function works and outputs a python dictionary which is very nice to work with. (It's `enum_value` is integers, but I later after my post found `nimpyEnumConvert` which I missed before which is exactly what I need here, so my second question is answered)

However, `unparse` doesn't compile with this error messages:

```
nimporter.NimCompileException:  type mismatch: got <SomeEnum>
 |      pyObjToProc(o, v)
 |    else:
 ->     unknownTypeCompileError(v)
 |  
 |  proc getListOrTupleAccessors(o: PPyObject):
At C:\Users\MegaIng\.nimble\pkgs\nimpy-0.1.1\nimpy.nim 561:28
```

I couldn't find something to modify that behavior. I did find a simple patch that works by adding a new `elif` inside of `pyObjToNim`:

```
  elif T is enum:
    var temp: string
    pyObjToNimStr(o, temp)
    v = parseEnum[T](temp)
```

This then works.

**Comment by yglukhov** [comment]
With recent changes to nimpy you can define custom marshalling in both ways, but I agree enums should be supported out of the box.

**Comment by MegaIng** [comment]
Aha, thank you for the fast fix!
