### ISSUE TITLE
How to stop the embedded python and environment?

### ISSUE THREAD

**Issue by arkanoid87** [yglukhov/nimpy#244]
Is there a reason why [Py_FinalizeEx](https://docs.python.org/3/c-api/init.html#c.Py_FinalizeEx) is not available / never called?

**Comment by yglukhov** [comment]
No. Is there a reason it should be?

**Comment by arkanoid87** [comment]
During a hunt for memory leaks in an application a developer might want to free all memory allocated by Python before exiting from the application

My case: https://github.com/SciNim/scinim/issues/8

**Comment by yglukhov** [comment]
Dunno, I don't find it too essential to be in nimpy, especially that it's 2 lines away anyway for those who need it, as you demonstrated in SciNim/scinim#8:
```nim
proc pyFinalize() =
  let Py_FinalizeEx = cast[proc():int{.pyfunc.}](py_lib.pyLib.module.symAddr("Py_FinalizeEx"))
  doAssert Py_FinalizeEx() == 0
```
