### ISSUE TITLE
Error when downloading Nimpy

### ISSUE THREAD

**Issue by nonimportant** [yglukhov/nimpy#250]
I get an error when i download Nimpy through nimble:
```
$ nimble install nimpy
```

```
Downloading https://github.com/yglukhov/nimpy using git
  Verifying dependencies for nimpy@0.2.0
parsejson.nim(515)       raiseParseErr
Error: unhandled exception: input(1, 0) Error: { expected [JsonParsingError]
```
When I try to download Nimpy on Windows however, it runs smoothly with no errors.
I'm on Linux Mint 20.3 Cinnamon, Cinnamon ver. 5.2.7.

**Comment by yglukhov** [comment]
Cannot reproduce. I believe it's a [nimble](https://github.com/nim-lang/nimble). Try compiling nimble in debug mode to see a more descriptive stack trace and report it to nimble repo.
