### ISSUE TITLE
Custom setting the path to python.exe (Windows)

### ISSUE THREAD

**Issue by ippaveln** [yglukhov/nimpy#267]
I would like to be able to set the path to the interpreter manually (for example, using an environment variable), since `findExe` does not work very well if the system has several interpreters from different places (including from msys)

In my opinion it is possible to change the `pythonLibHandleFromExternalLib` function.

**Comment by yglukhov** [comment]
`nimpy` doesn't use `python.exe`, but rather `libpython`, which path you can hint with `pyInitLibPath`
