### ISSUE TITLE
Hello world Segmentation fault

### ISSUE THREAD

**Issue by HugoGranstrom** [yglukhov/nimpy#271]
I tried running the hello world example:

```nim
import nimpy/py_lib
pyInitLibPath("/home/hugo/miniconda3/lib/libpython3.9.so.1.0")

import nimpy

proc greet(name: string): string {.exportpy.} =
  return "Hello, " & name & "!"
```
I compiled it like this:
`nim c --app:lib --out:mymodule.so --threads:on mymodule.nim`

And the Python code:
```
import mymodule
print(mymodule.greet("Hugo"))
```

But I'm getting this error when running the python file:
```
Traceback (most recent call last)
/home/hugo/.nimble/pkgs/nimpy-0.2.0/nimpy.nim(674) greetPy_wrapper
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
```

It somehow seems to be the `string` (`seq` also fails, so feels like something with the GC) that's causing this, because if I change the function to this version with an `int` instead, it works:
```nim
proc greet(name: int): string {.exportpy.} =
  return "Hello, " & $name & "!"
```
I have tried compiling with `arc` as well, but the same error.
Any idea why this is happening? 

## Versions
- PopOS (Ubuntu 22.04)
- Nim Compiler Version 1.6.6 [Linux: amd64]
- Anaconda Python 3.9.12

**Comment by yglukhov** [comment]
Please make absolutely sure you're using latest nimpy (delete and reinstall). Otherwise I cannot reproduce this.

**Comment by HugoGranstrom** [comment]
It seems like it was the `pyInitLibPath("/home/hugo/miniconda3/lib/libpython3.9.so.1.0")` that was the trouble. I fixed the thing that required me to have it, and now it works :) So it was just some local problems I guess.
