### ISSUE TITLE
Memory management issues. (workaround exists)

### ISSUE THREAD

**Issue by jiiihpeeh** [yglukhov/nimpy#275]
Since you wanted some error reported I'll give you one:

This file gets compiled as a static library for a Tauri app (Rust). 
https://github.com/jiiihpeeh/erroshavelimitstoo-Tauri/blob/main/src-tauri/callnim.nim

`nim c -d:release --app:staticLib --noMain -d:ssl --gc:boehm`

Without `--gc:boehm` it seems to crash when I call initialized python module after passing PNG as a base64 string to the fronted.

For instance without boehm:
loadScript(args) -> getPngFromSvg(svg) -> parse(args) -> crash

**Comment by yglukhov** [comment]
Your program crashes likely because `getPngFromSvg` returns `cstring` which in your case is unmanaged pointer to managed memory, that gets freed with `orc` or `refc`. Not related to `nimpy`. Feel free to prove me wrong.
