### ISSUE TITLE
have some trouble printing a module's version

### ISSUE THREAD

**Issue by edwardyeung** [yglukhov/nimpy#280]
here are my code

-- req.nim

```
import nimpy
let cv2 = pyImport("cv2")
echo cv2.__version__
```

-- error
C:\Users\yych\Desktop\t\req.nim(3, 11) Error: invalid token: _ (\95)

the problem is ... how can I call any functions/get any properties start with underline ... ?

**Comment by yglukhov** [comment]
Use `getAttr`. 
```nim
echo cv2.getAttr("__version__")
```
