### ISSUE TITLE
keeping long lived objects alive from python

### ISSUE THREAD

**Issue by root-11** [yglukhov/nimpy#281]
How to keep long-lived objects alive from python?

Most examples I've seen use `nimpy` in a functional capacity such as in this [example](https://github.com/root-11/root-11.github.io/blob/master/content/calling_nim_from_python.ipynb), but is it possible to use nimpy - just like sqlite - where a C object is instantiated once and kept alive for interaction in further subsequent calls?

In the example below `db` is an in-memory object that is kept alive for subsequent transactions:
```python
db = sqlite3.connect("file::memory:?cache=shared")
with db:
    cur = db.cursor()
    cur.execute(*args)
```
In numpy the same wrapping occurs:
```python
import numpy as np
numbers = np.zeros(2)  # c call.
numbers[0] = 1  # call to c object to update value.
```

I would be grateful for a brief example on how this may be done?

Something as simple as this would do:
```python
nimlist = example()  # loads integers 1..5 as C objects. These are never returned to python.
print( nim_index(3) )  # calls nimlist to index and returns a single value.
```

Kind regards
root-11

**Comment by root-11** [comment]
I believe this is a part of the game: [pybind11 keeping objects alive](https://stackoverflow.com/questions/59993357/pybind11-keeping-objects-alive) but I am clueless whether `nimpy` support this.

**Comment by yglukhov** [comment]
Most ref objects will do what you want. Just return your ref object from a nim function, then pass it to other nim functions.

Also you can try [exporting nim classes](https://github.com/yglukhov/nimpy/blob/1963283148d01f46ac789a83412afbb5d375cfad/tests/nimfrompy.nim#L144-L167)
