### ISSUE TITLE
Import local py file

### ISSUE THREAD

**Issue by agent10613** [yglukhov/nimpy#283]
Hi, I'm trying to import my python file into nim, via pyImport. Unfortunately, nimpy does not see this module, although both files are in the same place.

Can you please tell me what I'm doing wrong?

![image](https://github.com/yglukhov/nimpy/assets/127620783/2dcbbda4-bb61-4072-8495-0ead4d6b6e70)
C:\Users\User\User\WebstormProjects\untitled\main.nim(4) main
C:\Users\User\.nimble\pkgs\nimpy-0.2.0\nimpy.nim(935) pyImport
C:\Users\User\.nimble\pkgs\nimpy-0.2.0\nimpy\py_utils.nim(98) raisePythonError
Error: unhandled exception: <class 'ModuleNotFoundError'>: No module named 'mymod' [Exception]

**Comment by ctpeterson** [comment]
I've the same conundrum on Pop!_OS

Python code:
`#mymod.py
def hello_world():
    return "hello_world"`

Nim code:
`#test.nim
import  nimpy
let tst = pyImport("mymod")
echo tst.hello_world()`

Error:
`Error: unhandled exception: No callable attribute: hello_world [ValueError]`

**Comment by ctpeterson** [comment]
The following seemed to resolve this issue for me (CentOS). Following the example laid out in `tbuiltinpyfromnim.nim` & `builtinpyfromnim`:

# Python
`import sys`
`def hello_world():`
`    return "hello_world"`

# Nim
`let sys = pyImport("sys")`
`let os = pyImport("os")`
`discard sys.path.append(os.getcwd().to(string))`
`let tst {.used.} = pyImport("mymod")`
`echo tst.hello_world()`

The important thing for getting this to work on my end was importing `sys` in both modules & adding the local path to the Nim module with `sys` in the Nim module.

**Comment by yglukhov** [comment]
The only thing that should matter is python's `sys.path`.
```nim
import os, nimpy
discard pyImport("sys").path.append(getCurrentDir())
```
