### ISSUE TITLE
dynamic module does not define module export function (PyInit_pymodule)

### ISSUE THREAD

**Issue by HSS0x90** [yglukhov/nimpy#284]
ImportError: dynamic module does not define module export function (PyInit_pymodule)

**Comment by yglukhov** [comment]
Make sure your main nim file is called `pymodule.nim`

**Comment by HSS0x90** [comment]
Can you make a video tutorial for me?

**Comment by HSS0x90** [comment]
Oh, Thank you so much. Do you know this error "nimpy.CLRError: Unexpected error encountered: unable to invoke specified member: Invoke (0x80131604)", Here is the C# code that prints the Hello World message dialog box that I tried.
`
using System;
using System.Windows.Forms;

public class Program
{
    public static void Main()
    {
        MessageBox.Show("Hello World");
    }
}
`
This is the document I referenced: https://tishina.in/execution/pyd-execute-assembly

**Comment by yglukhov** [comment]
> Do you know this error

No, it has no relation to nimpy
