### ISSUE TITLE
 How to use it with multithreading?

### ISSUE THREAD

**Issue by cvanelteren** [yglukhov/nimpy#304]
I am playing around with Nim and python where I need to access python objects from different threads. In cython we get a handy `with gil` operator. Is there a way to access python objects in a similar way under Nimpy? Could you provide a minimal example?

Cheers!
C

**Comment by cvanelteren** [comment]
In particular I have this example I am running with:

<details> <summary> code </summary>

```Nim

import nimpy{.all.}, dynlib
import nimpy/py_lib {.all.}
import malebolgia

type PyGILState_STATE = enum PyGILState_LOCKED, PyGILState_UNLOCKED

{.pragma: pyfunc, cdecl, gcsafe.}
# initPyLibIfNeeded()
let
    m = pythonLibHandleForThisProcess()
    nx = pyImport("networkx")
    PyGILState_Ensure = cast[proc(): PyGILState_STATE {.pyfunc.}](m.symAddr("PyGILState_Ensure"))
    PyGILState_Release = cast[proc(s: PyGILState_STATE) {.pyfunc.}](m.symAddr("PyGILState_Release"))

template withGIL*(code) =
    let state = Py_GILState_Ensure()
    code
    Py_GILState_Release(state)

withGil:
    echo "in gil"

proc createG(idx: int) =
  echo idx
  withGil:
    var g = nx.path_graph(3)

var master = createMaster()
master.awaitAll:
  for idx in 0..1000:
    master.spawn createG(idx)
echo "done"
unloadLib(m)
```
</details>

**Comment by cvanelteren** [comment]
Figure it out, see for exaplanation [here](https://cvanelteren.github.io/post/release_gil/)

**Comment by Clonkk** [comment]
Just to clarify for future reader since the link is incorrect -> This is the correct link https://thefriendlyghost.nl/unleashedgil/

**Comment by cvanelteren** [comment]
My bad updated my website in the meantime ;-) Thanks!

**Comment by Clonkk** [comment]
It's a great article that would be deserving of being added to this repo as a test / example or documentation (IMO)

**Comment by cvanelteren** [comment]
Many thanks @Clonkk! Happy to provide a concrete test if @yglukhov wants to

**Comment by yglukhov** [comment]
@cvanelteren absolutely! Please do!

**Comment by cvanelteren** [comment]
See #307
