### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Yobmod** [yglukhov/nimpy#4]
Hi,
I tried out the example on Windows, but i get:

`ModuleNotFoundError: No module named 'mymodule'`

I tried compiling with the output as .dll or .pyd (like cython), or bootstrapping the .so myself, then i get:

`ImportError: dynamic module does not define module export function (PyInit_mymodule)`

I guess this is a windows issue as .dll files need a `dllexport `instruction. Can that be added as an option for windows compatibility?

**Comment by yglukhov** [comment]
Hi, thanks for the report. Unfortunately I don't have windows atm to test it, but here are the lines that define `PyInit_mymodule` for python 3 and `initmymodule` for python 2:
https://github.com/yglukhov/nimpy/blob/master/nimpy.nim#L591
https://github.com/yglukhov/nimpy/blob/master/nimpy.nim#L594

Please try patch those and see if it works for you, and then submit a PR.

**Comment by yglukhov** [comment]
Basically, try adding `stdcall` and `dynlib` pragmas.
