### ISSUE TITLE
GC Seg fault

### ISSUE THREAD

**Issue by raghur** [yglukhov/nimpy#48]
So I wrote a small module and then when I call it from python, it works fine if it's just a single call.

OTOH, if I call it in a loop - even say just 100 times, then after the 20th time there's a crash [on windows, the debug window opens, on linux I get a message about the GC]

I also tried building with `--gc:none` and in this case, the program completes successfully.

Are there guidelines/dos & donts in terms of what data can be returned from nim?

Happy to share code if you want to drop me an email at raghu dot nospam at gmail

**Comment by yglukhov** [comment]
Do you happen to use the non-devel version of nim that doesn't have this patch yet? https://github.com/nim-lang/Nim/pull/7885

**Comment by raghur** [comment]
Yes - I'm on nim 0.18 - `Nim Compiler Version 0.18.0 [Windows: amd64]`

Should I try the devel version?

**Comment by yglukhov** [comment]
Yes please

**Comment by yglukhov** [comment]
I assume that nails it. If not, feel free to reopen.

**Comment by raghur** [comment]
Works with the dev build without issues. Thanks!
Probably a good idea to put that on the README?

**Comment by yglukhov** [comment]
Kinda duplicate of #11
