### ISSUE TITLE
Numpy interop

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [yglukhov/nimpy#49]
Thanks for starting what looks like a very promising project. I very much believe that python owes much of its popularity by its easy of integration with a then dominant language, C. And for nims sake easy interop with the currently dominant python ecosystem seems vital to me!

Is there planned support for passing numpy arrays between nim and python?

Note that this is far more important to many users in practice (and I suspect far simpler to implement) than marshalling arbitrary datatypes back and forth. Typically you keep your interfaces between languages small anyway; but that does not mean you dont want to pass lots of data around.

From what it seems nim does not have much in the way of an ndarray object yet; but for instance even being able to pass an [n, 3] ndarray to a nim array of xyz points, and vice versa, with autogenerated runtime checks that this is a valid operation, and proper handling of memory management, would be a killer feature to me.

**Comment by apahl** [comment]
Hi Yuriy,  

I just want to thank you again for this great project!

I am getting very nice speedups (30x faster) for determining the Pearson correlation between two Numpy arrays in the [Nim implementation](https://gist.github.com/apahl/d673b0033794cc5f9514de639285592b) vs. the Scipy version using `RawPyBuffers`.

I find this very impressive as Numpy is supposed to be very fast already.

What do you think about collecting success stories like this somewhere?

Kind regards,  
Axel
