### ISSUE TITLE
Error: usage of 'isNil' is a user-defined error

### ISSUE THREAD

**Issue by flenniken** [yglukhov/nimpy#52]
I'm updating my code from nim 0.18 to 0.19 and am running into this error:

../../nimpy/nimpy.nim(740, 14) Error: usage of 'isNil' is a user-defined error

Nim changed the way they handle nil for 0.19, does nimpy need to be updated?

**Comment by yglukhov** [comment]
> does nimpy need to be updated?

Yes, seems like you've got an old nimpy version

**Comment by yglukhov** [comment]
> Do I have the correct version?

Apparently, no. There's no `isNil` at line 740: https://github.com/yglukhov/nimpy/blob/master/nimpy.nim#L740. Try removing the package from nimble dir, and installing it again. Nimble should usually prompt you when a "latest" version is already installed and you want to reinstall anyway. If that's the case, always answer to reinstall.

> I'm running nimpy 0.1.0

Unfortunately all nimpy versions are tagless with version `0.1.0`, so the version is irrelevant.

**Comment by flenniken** [comment]
I'm pretty sure I was prompt and I said to reinstall.  I took you your advice and found the nimpy package on my system and deleted it then installed it again.  Now it works, thank you.

I found the directory on my mac by running "which nim", then looking in the pkgs dir.

Maybe nimble skipped the reinstall because the version number is the same.
