### ISSUE TITLE
[question] How to create tuple inside of nim ?

### ISSUE THREAD

**Issue by vlad1777d** [yglukhov/nimpy#59]
Sorry, maybe stupid question, but can't figure out how to create tuple ?
Tried many-many ways, but unsuccessfully...

I'm newbie in Nim.

![screenshot from 2018-11-01 06-10-52](https://user-images.githubusercontent.com/12682937/47832247-f59ace00-dd9c-11e8-9f44-c8c28c1f2dc1.png)

**Comment by sinkingsugar** [comment]
Straight nim tuple worked for me, e.g.:
`fig = plt.figure(figsize=(5000 div dpi, 800 div dpi), dpi=dpi)`
`var mytuple = (5000 div dpi, 800 div dpi)`
Nim compiler assumes `(`*`)` as tuple basically and seems to work straight in nimpy!

**Comment by yglukhov** [comment]
Generally you don't want to do that, but here's one of possible ways:
```nim
import nimpy

let myTuple = pyBuiltinsModule().`tuple`((123, "hi"))
echo myTuple
```

**Comment by vlad1777d** [comment]
thanks
