### ISSUE TITLE
Mapping nim names to different python names

### ISSUE THREAD

**Issue by flenniken** [yglukhov/nimpy#6]
I am trying to create a nim exe and python module with the same name.  I want to expose snake case names in the python module and camel case in the nim code. I also want the python module to contain a \_\_version\_\_ attribute.

I've tried many different ways to achieve this but I haven't found something that works.  I made a simple example to show what I am trying to do. 

If the exportpy pragma supported symbol renaming like the exportc pragma does, I think that would solve my case.  Do you have plans to support this?

The commented out lines so what I want to do.

```code
$ cat t.nim

import nimpy

# const version {.exportpy: "__version__".} = "1.2.3"
const version = "1.2.3"

# proc fooBar*(): string {.exportpy: "foo_bar".} = 
#   result = "fooBar"

proc fooBar*(): string {.exportpy.} = 
  result = "fooBar"
  
when not defined(buidingLib):
  when isMainModule:
    echo fooBar()

$ cat test.py

import t
# print t.__version__
# print t.foo_bar()
print t.fooBar()

$ cat t.nimble 

# Package

version       = "1.2.3"
author        = "Steve Flenniken"
description   = "Example nim exe and python module with the same name."
license       = "MIT"

# Dependencies

requires "nim >= 0.17.2"

task b, "Build exe and python module":
  exec "nim c -d:buidingLib --threads:on --tlsEmulation:off --app:lib --out:t.so t"
  exec "nim c -r t"
  exec "python test.py"

**Comment by yglukhov** [comment]
Please note that currently you can apply `exportpy` pragma only to proc definitions.
