### ISSUE TITLE
[question] proc dict argument

### ISSUE THREAD

**Issue by juancarlospaco** [yglukhov/nimpy#66]
Hi, thanks for the epic work, it works nicely.

I need to create a `proc` that needs to take a Python `dict()`.

dict is of unknown length, all dict item values are JSON-compatible like `int`, `bool`, `str`, `float`, etc, 

I have search the doc, examples, and tests and cant find which type to use on the Nim code.

**Nim**
```nim
import nimpy

proc needs_dict_argument( dict_arg: WhatToPutHere ) {.exportpy.} =
  # does stuff with dict_arg

```

**Python**
```python
from nimpy_module import needs_dict_argument

needs_dict_argument( {"foo": 666, "bar": False, "baz": 42.0} )
```

`WhatToPutHere` is what I dont understand. Ive tried `seq`, `openArray` & `Table` but didnt work. Thanks :grey_exclamation: 
:cat:

**Comment by yglukhov** [comment]
Either use latest fix, or
```nim
proc needs_dict_argument( dict_arg: PyObject ) {.exportpy.} =
  echo dict_arg.toJson() # Shortcut :)
  echo dict_arg["foo"].to(int)
  echo dict_arg["bar"].to(bool)
  # etc...
```

**Comment by juancarlospaco** [comment]
Thank you very much, awesome quick responses :grey_exclamation: The speed of Nimpy is unrivaled, I uninstalled Cython like for ever. 
:joy_cat: :+1:

**Comment by yglukhov** [comment]
Yay! Now how about a blog post to /r/python? ;)

**Comment by juancarlospaco** [comment]
I am not much of a Blogger (I sux at writing), but I will investigate, I think thats the Reddit ?, I will signup.

BTW I made:

- https://github.com/juancarlospaco/faster-than-requests#faster-than-requests
- https://github.com/juancarlospaco/faster-than-csv#faster-than-csv
:laughing:
