### ISSUE TITLE
unhandled exception: Symbol not loaded: PyObject_GetBuffer [Exception]

### ISSUE THREAD

**Issue by retsyo** [yglukhov/nimpy#74]
I use your code
```nim
import nimpy
let os = pyImport("os")
echo "Current dir is: ", os.getcwd().to(string)

# sum(range(1, 5))
let py = pyBuiltinsModule()
let s = py.sum(py.range(0, 5)).to(int)
assert(s == 10)
```
with 
```
Nim Compiler Version 0.19.9 [Windows: amd64]
Compiled at 2018-12-13
Copyright (c) 2006-2018 by Andreas Rumpf
```
in MSYS2 on win7 64 bits

when I copy the EXE file into python 64bits directory
```
E:\prg\py\Anaconda3_64>a
a.nim(2)                 a
nimpy.nim(1002)          pyImport
py_lib.nim(404)          initPyLibIfNeeded
py_lib.nim(369)          initPyThreadFrame
py_lib.nim(364)          initPyLib
py_lib.nim(152)          loadPyLibFromModule
py_lib.nim(133)          symNotLoadedErr
Error: unhandled exception: Symbol not loaded: PyObject_GetBuffer [Exception]
```

**Comment by yglukhov** [comment]
That's strange, `PyObject_GetBuffer` should be in all python build, afaik. Can you try comment this line out and see how far will you go? https://github.com/yglukhov/nimpy/blob/master/nimpy/py_lib.nim#L187

**Comment by retsyo** [comment]
I found the reason: in my Anaconda3_64, there are both `python3.dll` and `python36.dll`.  `PyObject_GetBuffer` and some functions does not live in `python3.dll`. However I don't know how `python3.dll` come here
