### ISSUE TITLE
Exporting in sub modules

### ISSUE THREAD

**Issue by flenniken** [yglukhov/nimpy#8]
Do all your python exports need to be in the main file?  The procedures I mark with exportpy in imported nim modules to not appear in the python module.  No compiler errors.

**Comment by yglukhov** [comment]
Currently it is done so that the functions end up defined in their module with its python name matching nim name. That means you could implement several "python" modules in a single so. E.g.
```nim
# main.nim
import foo # foo module has some pyexported procs
import bar # bar module has some pyexported procs
```
```
# Compile the so as you normally would
nim c --threads:on --tlsEmulation:off --app:lib --out:main.so main
# Create a foo symlink
ln -s main.so foo.so
# Create a bar symlink
ln -s main.so bar.so
```
```py
# mymodule.py
import foo
import bar
```

Please tell me if that works for you.

**Comment by flenniken** [comment]
I can make it work by creating stubs to all my python exports in one nim module.  

However, I do not think it is a common need to create multiple python modules from one .so file.  It is common to split your project into multiple nim files and have the public interface in different files.  So I think it would be more useful to only support one python module per .so file.  

You could create multiple .so files from the same nim source code by targeting different names when compiling, (if you change the code to support this).

```
nim c ... -d:buidingFoo --out:bin/foo.so foo/foo
nim c ... -d:buidingBar --out:bin/bar.so foo/foo
```

Being able to specify the python module name from the .so name (the --out parameter) is also useful for the case where you want support variables in the python side that you cannot currently export.  For example, supporting "\_\_version\_\_" in a python module.

One way to support "\_\_version\_\_" is by creating a foo_lib.so then making a foo.py module like the following example.  This allows users to see the same name, foo as the python name and the nim name as well as supporting \_\_version\_\_.

```
nim c ... -d:buidingLib --out:bin/foo_lib.so foo/foo

# foo.nim
proc getVersion(): string {.exportpy.} = 
	result = "1.2.3"

# foo.py
import foo_lib
__version__ = foo_lib.getVersion()

# test.py
import foo
print foo.__version__
```

**Comment by yglukhov** [comment]
One feature that I was planning is to allow passing identifiers to `exportpy`, so basically your problem would be solved like this:
```nim
import myModule # defines some procs like foo, bar, baz
import nimpy

exportpy foo, bar, baz

# Another plausible way (no idea if nim allows this):
exportpy myModule # export all public symbols from myModule
```

**Comment by Sann0** [comment]
Is there any progress on this yet? My Module gets pretty big and is confusing with one file.

**Comment by yglukhov** [comment]
Fixed differently.
