### ISSUE TITLE
garbage collectors

### ISSUE THREAD

**Issue by jabbalaci** [yglukhov/nimpy#82]
I read about nimpy here: https://robert-mcdermott.gitlab.io/posts/speeding-up-python-with-nim/ . At the bottom of that page there is this remark:

"UPDATE 2019-01-23: On the Nim forum there was a comment about a potential problem with the Nim and Python garbage collectors interfering with each other. The creator of Nim, Andreas Rumpf, responded that compiling with the “–gc:regions” flag when creating an extension module will eliminate this risk. I’ve updated the article to include this detail."

If it's true, then "--gc:regions" should be added to the README.

**Comment by yglukhov** [comment]
I don't recommend using `--gc:regions`, and I can't easily explain the reason, sorry.
