### ISSUE TITLE
Load python 3.6 x86 error.

### ISSUE THREAD

**Issue by slangmgh** [yglukhov/nimpy#85]
Because python3.dll with python 3.6 x86 version doesn't export function PyObject_GetBuffer, so it cannot load the python3.dll.
```
t93.nim(4)               t93
nimpy.nim(1039)          pyBuiltinsModule
py_lib.nim(404)          initPyLibIfNeeded
py_lib.nim(369)          initPyThreadFrame
py_lib.nim(364)          initPyLib
py_lib.nim(152)          loadPyLibFromModule
py_lib.nim(133)          symNotLoadedErr
Error: unhandled exception: Symbol not loaded: PyObject_GetBuffer [Exception]
Error: execution of an external program failed: 't93.exe '
```

If we can put the python version like:
```nim
    for v in ["3.6", "3.7", "3", "3.5", "", "2", "2.7"]:
        when defined(macosx):
            yield "libpython" & v & ".dylib"
            yield "libpython" & v & "m.dylib"
```

The problem can be fixed, and will not arise any issue.

**Comment by BontaVlad** [comment]
I think a better way of dealing with this is in ```py_lib.nim``` and instead of ```load PyObject_GetBuffer``` that expects GetBuffer to be available to a more defensive ```maybeLoad``` and then handle the case if GetBuffer is missing.

**Comment by yglukhov** [comment]
Yeah, another way is to reimplement buffer api in nimpy, because buffer callbacks were available in the type objects before buffer protocol was introduced. But it is surely more complicated, and likely not worth it.

**Comment by slangmgh** [comment]
@yglukhov 
This bug is not fixed.

The following code:
```nim
import nimpy

let py = pyBuiltinsModule()
py.print "hello world"
```

gives the result:
```nim
Traceback (most recent call last)
t95.nim(3)               t95
nimpy.nim(1190)          pyBuiltinsModule
py_lib.nim(418)          initPyLibIfNeeded
py_lib.nim(405)          initPyThreadFrame
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by slangmgh** [comment]
@yglukhov 

Still not ideal fix, it just skip check the PyObject_GetBuffer and leave it as nil, so functions in RawBuffer is not usable.

Possible add check for PyObject_GetBuffer symbol after loadLib in pythonLibHandleFromExternalLib:

```nim
    for lib in libPythonNames():
        result = loadLib(lib, true)
        if not result.isNil and not result.symAddr("PyObject_GetBuffer").isNil:
            break
```

It doesn't break anything, but make the everything works.
