### ISSUE TITLE
Passing data back to Python

### ISSUE THREAD

**Issue by andreaferretti** [yglukhov/nimpy#9]
In my use case, I have a function that creates some kind of object that eventually needs to be passed back to python. There is no need be able to do anything with in python, except pass it back to other nim functions. Something like this:

```nim
# module.nim
import nimpy

type MyObject = object
  a, b, c: int
  d: string

proc makeMyObject(a, b, c: int, d: string): MyObject {.exportpy.} =
  MyObject(a: a, b: b, c: c, d: d)

proc doSomethingWithMyObject(obj: MyObject) {.exportpy.} =
  echo obj.d
```

```python
import module

x = module.makeMyObject(1, 2, 3, "hi")
module.doSomethingWithMyObject(x)
```

Unfortunately trying to compile the nim file gives 
```
usage of makeMyObjectPy_wrapper is a user-defined error
```

I just need to return the result as an opaque type from the Python point of view. Is there a way to do something like that?

**Comment by andreaferretti** [comment]
Thank you, that was quick!

Unfortunately, if I now try to compile the above example with the latest nimpy, I get

```
/Users/andrea/.nimble/pkgs/nimpy-0.1.0/nimpy.nim(809, 9) Error: internal error: expr: param not init v_161867
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

This happens with both devel and 0.18

**Comment by andreaferretti** [comment]
In fact, line 809 is `v` in

```nim
proc nimValueToPy[T](v: T): PyObject {.inline.} =
    when T is void:
        v
        incRef(pyLib.Py_None)
        pyLib.Py_None
    elif T is string:
      strToPyObject(v)
  ...
```

Does it make sense to have just the statement `v` when `T` is void?

**Comment by yglukhov** [comment]
Thanks, fixed!

**Comment by andreaferretti** [comment]
One last question: if the type I am returning is a `ref`, we get to https://github.com/yglukhov/nimpy/blob/master/nimpy.nim#L776

```nim
    else:
        unknownType(v)
```

but `unknwonType` is declared as

```nim
proc unknownType() {.inline.} = discard
```

with no arguments. This leads to an error such as

```nim
/Users/andrea/.nimble/pkgs/nimpy-0.1.0/nimpy.nim(851, 20) Error: type mismatch: got <PNG>
but expected one of: 
proc unknownType()
```

Could it make sense to have another case for refs and ptrs? (Should then the refcount for python be linked somehow with the refcount for nim?)

**Comment by andreaferretti** [comment]
I am not familiar with the C extension API, but it seems that one should use `O&` as a format for `Py_BuildValue`, which lets one provide a generic converter function that takes a `void *` and return a PyObject. I am not sure how to write the latter yet, though

**Comment by andreaferretti** [comment]
Apparently [capsules](https://docs.python.org/3.1/c-api/capsule.html) are the right data type to pass an opaque pointer back and forth

**Comment by yglukhov** [comment]
Fixed.

**Comment by andreaferretti** [comment]
Wow, you are really fast! :-D Thank you again for all your help!
