### ISSUE TITLE
Convert Python Tuples to Nim Type

### ISSUE THREAD

**Issue by zaferarican** [yglukhov/nimpy#90]
I am working on some examples to access Numpy Data ([nimpy_numpy_examples](https://github.com/zaferarican/nimpy_numpy_examples)). I use ".to" function in Nimpy for many pyobject types but I could not find a way to convert Python Tuple (for example in numpy.shape) to a data type in Nim. 

For now what I do is 
```nim
let py = pyBuiltinsModule()
var shape = py.list(o.shape)
echo "[",shape[0],",",shape[1],"]"  
```
Is there another way, for example using just the **to** function?
In general, how can we convert Python tuples to a nim data type?

**Comment by yglukhov** [comment]
Now you can use `o.shape.to(seq[int])`

**Comment by zaferarican** [comment]
Super. Thanks.
